### PR TITLE
performance fix: prevent gcd infinite loop with floating-point step values

### LINKED ISSUE #3919: [Bug]: RangeError: Maximum call stack size exceeded when loading large workflow
### Frontend Version

I tried with 1.19.9 & 1.20.2

### Expected Behavior

Workflow should load even if it's large and with many linked connections

### Actual Behavior

When loading a large workflow (≈1400+ nodes, ≈12,000 links), the frontend crashes with the error:
RangeError: Maximum call stack size exceeded

Image

### Steps to Reproduce

Install latest ComfyUI backend and frontend

Launch ComfyUI

Load the attached *.json workflow: 

[QC_Batch_Juggy_001_noCustomNodes.json](https://github.com/user-attachments/files/20266206/QC_Batch_Juggy_001_noCustomNodes.json)

Observe the stack overflow and crash

### Debug Logs

```powershell
Checkpoint files will always be loaded safely.
Total VRAM 16376 MB, total RAM 65234 MB
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
Using pytorch attention
Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
ComfyUI version: 0.3.34
Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
Downloading frontend(Comfy-Org_ComfyUI_frontend) version(1.20.2) to (C:\Comfyui\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.20.2)
[Prompt Server] web root: C:\Comfyui\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.20.2

Import times for custom nodes:
   0.0 seconds: C:\Comfyui\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188

(nothing after that)
```

### Browser Logs

Image

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/20266211/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

### Other Information

I’ve already:

- Removed all custom nodes
- Validated that the graph has no cycles
- Repaired all broken links (inputs match outputs)
- Rounded all pos and size values
- Removed all groups

### PR DESCRIPTION
**Pull request by jtydhr88**
## Summary

report and fix https://github.com/Comfy-Org/ComfyUI_frontend/issues/3919

- Convert recursive gcd to iterative to avoid stack overflow
- Add epsilon tolerance (1e-10) for floating-point precision issues

This fixes workflow loading hangs when node trying merge values like 0.01 and 0.001, which caused the original recursive gcd to run indefinitely due to floating-point modulo never reaching exactly zero.

please notice, we need both iterative and epsilon together to fix this gcd issue

Call Chain

PrimitiveNode.onAfterGraphConfigured
  → #mergeWidgetConfig
    → #isValidConnection
      → mergeIfValid
        → mergeInputSpec
          → mergeNumericInputSpec
            → lcm(step1, step2)
              → gcd(a, b)  ← Problem here

Why It Happened
When some nodes connect to multiple nodes, it may merge values using LCM, which internally calls GCD.

Original recursive implementation:
```
export const gcd = (a: number, b: number): number => {
   return b === 0 ? a : gcd(b, a % b)
}
```

Issues:
1. Stack Overflow: Recursive calls with many nodes exhausted the call stack.
2. Floating-Point Precision: For values like gcd(0.01, 0.001):
 ` 0.01 % 0.001 = 0.0009999999999999994  // Not exactly 0!`
3. Due to Ifloating-point representation, the modulo never reaches exactly zero, causing hundreds or thousands of iterations.

### before

https://github.com/user-attachments/assets/cca4342c-a882-4590-a8d4-1e0bea19e5b7

### fix with only iterative, without epsilon

https://github.com/user-attachments/assets/1dc52aa4-a86a-40b5-8bac-904094c4c36b

### final fix with iterative and epsilon
https://github.com/user-attachments/assets/7b868b50-c3c9-4be4-8594-27cecbc08a26

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-7258-performance-fix-prevent-gcd-infinite-loop-with-floating-point-step-values-2c46d73d3650818cbe8cf455c934a114) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/utils/mathUtil.ts [hunk 1]
```diff
@@ -2,14 +2,40 @@ import type { ReadOnlyRect } from '@/lib/litegraph/src/interfaces'
...
+  const epsilon = 1e-10
+  const maxIterations = 100
+
+  let iterations = 0
+  while (b > epsilon && iterations < maxIterations) {
+    const temp = b
+    b = a % b
+    a = temp
+    iterations++
+  }
```
[the remark this answers is not in the document]
Comment (jtydhr88) [reply src/utils/mathUtil.ts:34]: in fact, no, 
If we throw error when reached maxIterations, that means loading workflow will fail to user, which not being expected for user

File: src/utils/mathUtil.ts [hunk 2]
```diff
@@ -2,14 +2,40 @@ import type { ReadOnlyRect } from '@/lib/litegraph/src/interfaces'
...
+  // For floating-point numbers, use tolerance-based comparison
+  // This prevents infinite loops due to floating-point precision issues
+  const epsilon = 1e-10
+  const maxIterations = 100
+
+  let iterations = 0
+  while (b > epsilon && iterations < maxIterations) {
+    const temp = b
+    b = a % b
+    a = temp
```
Comment (DrJKL) [inline src/utils/mathUtil.ts]: Optional: 
```suggestion
    [a, b] = [b, a % b]
```

File: src/utils/mathUtil.ts [hunk 3]
```diff
@@ -2,14 +2,40 @@ import type { ReadOnlyRect } from '@/lib/litegraph/src/interfaces'
...
  *
  * @param a - The first number.
  * @param b - The second number.
  * @returns The GCD of the two numbers.
  */
 export const gcd = (a: number, b: number): number => {
-  return b === 0 ? a : gcd(b, a % b)
+  // Use absolute values to handle negative numbers
+  a = Math.abs(a)
+  b = Math.abs(b)
```
Comment (DrJKL) [inline src/utils/mathUtil.ts]: Nit: I don't like reassigning parameters.
Could you add local variables?

**Review by DrJKL — DISMISSED** [review]

File: src/utils/mathUtil.ts (hunk 2 above)
Comment (jtydhr88) [reply src/utils/mathUtil.ts]: fixed

File: src/utils/mathUtil.ts (hunk 3 above)
Comment (jtydhr88) [reply src/utils/mathUtil.ts]: fixed

**Review by DrJKL — APPROVED** [review]
