### PR TITLE
Fix client => canvas position conversion

### LINKED ISSUE #3539: [Bug]: Drag a node from the sidebar, but it just appended at a random position.
### Frontend Version

1.16.9

### Expected Behavior

After dragged and dropped the nodes, it should append at where the cursor pointer is.

### Actual Behavior

It just appears at a random position. I tried several times and found that it was appended at a very far position.

https://github.com/user-attachments/assets/f3c3a297-8750-45f8-9509-dfb36230d88c

### Steps to Reproduce

Drag a node from the sidebar.

### Debug Logs

```powershell
There are no logs for this operation.
```

### Browser Logs

There are no logs for this operation.

### Setting JSON

```json
{
    "Comfy.TutorialCompleted": true,
    "Comfy.QueueButton.BatchCountLimit": 10000,
    "AGL.Locale": "zh-CN",
    "pysssss.SnapToGrid": true,
    "Comfy.Extension.Disabled": [
        "pysssss.Locking",
        "AIGODLIKE.Translation",
        "pysssss.SnapToGrid",
        "pysssss.ImageFeed",
        "pysssss.ShowImageOnMenu"
    ],
    "Comfy.ColorPalette": "dark",
    "Comfy.Queue.ImageFit": "contain",
    "LiteGraph.ContextMenu.Scaling": false,
    "Comfy.NodeBadge.NodeIdBadgeMode": "Show all",
    "Comfy.NodeBadge.NodeSourceBadgeMode": "Show all",
    "Comfy.Workflow.WorkflowTabsPosition": "Topbar",
    "Comfy.Locale": "en"
}
```

### What browsers do you use to access the UI ?

Google Chrome

### Other Information

_No response_

### LINKED ISSUE #7616: Node from node library - drag and drop bug
### Expected Behavior

I don't know what changed in the last build, but I'm having trouble dragging the node into the workspace. I have the Node Library on the left, and I use the mouse to drag the node into the workspace. Now when I drag the node in, it appears at a random point in the workspace, not where I release it with the mouse. What could be the reason?

### Actual Behavior

Image

### Steps to Reproduce

Drag a node from the Node Library into the workspace and drop it. The node will appear elsewhere.

### Debug Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-04-16 08:19:54.684
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: I:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: I:\ComfyUI_windows_portable\ComfyUI
** ComfyUI Base Folder Path: I:\ComfyUI_windows_portable\ComfyUI
** User directory: I:\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: I:\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: I:\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   3.4 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Total VRAM 24576 MB, total RAM 65289 MB
pytorch version: 2.6.0+cu124
xformers version: 0.0.29.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers attention
Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
ComfyUI version: 0.3.28
ComfyUI frontend version: 1.15.13
[Prompt Server] web root: I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\comfyui_frontend_package\static
I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
unknown args: ['--preview-method', 'taesd', '--use-flash-attention']
Found GPU NVIDIA GeForce RTX 3090
Web extensions folder found at I:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
Adding I:\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V8.11)
### Loading: ComfyUI-Impact-Pack (V8.11)
[Impact Pack] Wildcards loading done.
Loaded ImpactPack nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
I:\ComfyUI_windows_portable\ComfyUI\web/extensions/core/uploadImage.js
File already contains the necessary modifications.✅
File 'I:\ComfyUI_windows_portable\ComfyUI\folder_paths.py' updated successfully.✅
Original code block not found.❌
Using sageattn
Using sageattn
Using sageattn
[Crystools INFO] Crystools version: 1.22.1
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i9-13900K - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3090
[Crystools INFO] NVIDIA Driver: 572.83
Flow - 0.5.2: Downloading and Upading Flows
Flow - 0.5.2: Flows have been updated successfully.
[ComfyUI-Easy-Use] server: v1.2.9 Loaded
[ComfyUI-Easy-Use] web root: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
PyTorch version 2.6.0+cu124 available.
JAX version 0.4.37 available.
ComfyUI-GGUF: Partial torch compile only, consider updating pytorch
[ComfyUI-HakuImg]-|08:20:07|-INFO: Check HakuImg requirements
[ComfyUI-HakuImg]-|08:20:07|-INFO: Check HakuImg requirements done
new registry table has been added: preprocessor_classes
new registry table has been added: adaptor_classes
I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\rotary_embedding_torch\rotary_embedding_torch.py:35: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)

I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\rotary_embedding_torch\rotary_embedding_torch.py:268: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)

new registry table has been added: lid_predictor_classes
I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 2.0.5 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

### Loading: ComfyUI-Impact-Pack (V8.11)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Subpack (V1.2.9)
[Impact Subpack] ultralytics_bbox: I:\ComfyUI_windows_portable\ComfyUI\models\ultralytics\bbox
[Impact Subpack] ultralytics_segm: I:\ComfyUI_windows_portable\ComfyUI\models\ultralytics\segm
### Loading: ComfyUI-Inspire-Pack (V1.18)
jjk_util loding
Total VRAM 24576 MB, total RAM 65289 MB
pytorch version: 2.6.0+cu124
xformers version: 0.0.29.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
theUpsiders Logic Nodes: Loaded
### Loading: ComfyUI-Manager (V3.31.10)
[ComfyUI-Manager] network_mode: public
### ComfyUI Revision: 3332 [a14c2fc3] *DETACHED | Released on '2025-04-13'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available False
edit_mask.available True
## clip_interrogator_model not found: I:\ComfyUI_windows_portable\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: I:\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: I:\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
MiniCPMNode.available
Scenedetect.available False
FishSpeech.available False
SenseVoice.available False
Whisper.available False
fal-client## OK
FalVideo.available
 --------------
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo
MultiGPU: Found ComfyUI-LTXVideo, creating compatible MultiGPU nodes
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
MultiGPU: Found ComfyUI-Florence2, creating compatible MultiGPU nodes
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
MultiGPU: Module ComfyUI_bitsandbytes_NF4 not found - skipping
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_bitsandbytes_nf4
MultiGPU: Module comfyui_bitsandbytes_nf4 not found - skipping
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
MultiGPU: Found x-flux-comfyui, creating compatible MultiGPU nodes
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MMAudio
MultiGPU: Module ComfyUI-MMAudio not found - skipping
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mmaudio
MultiGPU: Module comfyui-mmaudio not found - skipping
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
MultiGPU: Found ComfyUI-GGUF, creating compatible MultiGPU nodes
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
MultiGPU: Found PuLID_ComfyUI, creating compatible MultiGPU nodes
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
MultiGPU: Found ComfyUI-HunyuanVideoWrapper, creating compatible MultiGPU nodes
MultiGPU: Checking for module at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
MultiGPU: Found ComfyUI-WanVideoWrapper, creating compatible MultiGPU nodes
MultiGPU: Registration complete. Final mappings: DeviceSelectorMultiGPU, HunyuanVideoEmbeddingsAdapter, MergeFluxLoRAsQuantizeAndLoaddMultiGPU, UNETLoaderMultiGPU, VAELoaderMultiGPU, CLIPLoaderMultiGPU, DualCLIPLoaderMultiGPU, TripleCLIPLoaderMultiGPU, CheckpointLoaderSimpleMultiGPU, ControlNetLoaderMultiGPU, LTXVLoaderMultiGPU, Florence2ModelLoaderMultiGPU, DownloadAndLoadFlorence2ModelMultiGPU, LoadFluxControlNetMultiGPU, UnetLoaderGGUFMultiGPU, UnetLoaderGGUFDisTorchMultiGPU, UnetLoaderGGUFAdvancedMultiGPU, UnetLoaderGGUFAdvancedDisTorchMultiGPU, CLIPLoaderGGUFMultiGPU, CLIPLoaderGGUFDisTorchMultiGPU, DualCLIPLoaderGGUFMultiGPU, DualCLIPLoaderGGUFDisTorchMultiGPU, TripleCLIPLoaderGGUFMultiGPU, TripleCLIPLoaderGGUFDisTorchMultiGPU, PulidModelLoaderMultiGPU, PulidInsightFaceLoaderMultiGPU, PulidEvaClipLoaderMultiGPU, HyVideoModelLoaderMultiGPU, HyVideoVAELoaderMultiGPU, DownloadAndLoadHyVideoTextEncoderMultiGPU, WanVideoModelLoaderMultiGPU, WanVideoVAELoaderMultiGPU, LoadWanVideoT5TextEncoderMultiGPU
vtracer module found. SVG conversion will use vtracer.
Use STYLE(weight_interpretation, normalization) at the start of a prompt to use advanced encodings
Weight interpretations available: comfy,A1111,compel,comfy++,down_weight,perp
Normalization types available: none,mean,length,length+mean
[WARNING] PromptControl (LEGACY VERSION): You are using UNMAINTAINED NODES. Please migrate to a supported version of Prompt Control
No translation dir found!
I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

Nvidia APEX normalization not installed, using PyTorch LayerNorm
Nvidia APEX normalization not installed, using PyTorch LayerNorm
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[ReActor] - STATUS - Running v0.5.2-a2 in ComfyUI
Torch version: 2.6.0+cu124
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
scepter [INFO] 2025-04-16 08:20:12,275 [File: import_utils.py Function: <module> at line 92]  PyTorch version 2.6.0+cu124 Found.
scepter.ast [INFO] 2025-04-16 08:20:12,279 [File: ast_utils.py Function: load_index at line 479]  Building ast index from scanning every file!
scepter.ast [INFO] 2025-04-16 08:20:12,280 [File: ast_utils.py Function: get_files_scan_results at line 443]  AST-Scanning the path "I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\scepter" with the following sub folders ['modules', 'studio', 'tools', 'workflow']
scepter.ast [INFO] 2025-04-16 08:20:12,594 [File: ast_utils.py Function: get_files_scan_results at line 465]  Scanning done! A number of 247 components indexed or updated! Time consumed 0.31462907791137695s

From Bmad Custom Nodes
 Loaded 125 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (50)
  + color clip ade20k node (1)
  + extension dependent nodes (2)

------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ckpts path: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using symlinks: False
[I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']

### [START] ComfyUI AlekPet Nodes v1.0.59 ###
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading]
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode, ChatGLM4InstructNode, ChatGLM4InstructMediaNode [Loading]
Node -> DeepLXTranslateNode: DeepLXTranslateCLIPTextEncodeNode, DeepLXTranslateTextNode [Failed]
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
Node -> PoseNode: PoseNode [Loading]

* Nodes have been temporarily disabled due to the error *
DeepLXTranslateNode -> Error path to 'Golang (Go)' not exists: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\DeepLXTranslateNode\go\bin

### [END] ComfyUI AlekPet Nodes ###

Optimum library found. GPTQ model loading enabled (requires suitable backend).
HiDream: Successfully registered with ComfyUI memory management
--------------------------------------------------
HiDream Sampler Node Initialized
Available Models: ['full-nf4', 'dev-nf4', 'fast-nf4', 'full', 'dev', 'fast']
--------------------------------------------------
Ib Custom Nodes: Loaded
👑 Mokkaboss1 59 Custom Nodes: Loaded
👑 Mokkaboss1 59 Custom Nodes: Loaded
config.json not found, use config.json.template
# 😺 ComfyUI_OmniGen_Wrapper: -> Success loaded 1 nodes.

     ██████╗ ██╗   ██╗ █████╗ ███╗   ██╗    ██████╗ ███╗   ██╗
     ██╔══██╗╚██╗ ██╔╝██╔══██╗████╗  ██║   ██╔═══██╗████╗  ██║
     ██████╔╝ ╚████╔╝ ███████║██╔██╗ ██║   ██║   ██║██╔██╗ ██║
     ██╔══██╗  ╚██╔╝  ██╔══██║██║╚██╗██║   ██║   ██║██║╚██╗██║
     ██║  ██║   ██║   ██║  ██║██║ ╚████║   ╚██████╔╝██║ ╚████║
     ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═════╝ ╚═╝  ╚═══╝
████████╗██╗  ██╗███████╗   ██╗███╗   ██╗███████╗██╗██████╗ ███████╗
╚══██╔══╝██║  ██║██╔════╝   ██║████╗  ██║██╔════╝██║██╔══██╗██╔════╝
   ██║   ███████║█████╗     ██║██╔██╗ ██║███████╗██║██║  ██║█████╗
   ██║   ██╔══██║██╔══╝     ██║██║╚██╗██║╚════██║██║██║  ██║██╔══╝
   ██║   ██║  ██║███████╗   ██║██║ ╚████║███████║██║██████╔╝███████╗
   ╚═╝   ╚═╝  ╚═╝╚══════╝   ╚═╝╚═╝  ╚═══╝╚══════╝╚═╝╚═════╝ ╚══════╝

             ⚡ R Y A N   O N   T H E   I N S I D E ⚡


Checking for AdvancedLivePortrait at: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
Checking for Advanced-ControlNet at: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Checking for AnimateDiff-Evolved at: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
[RyanOnTheInside] Copying extension file: widget_hotkey.js
[tinyterraNodes] Loaded
All packages from requirements.txt are installed and up to date.
llama-cpp installed
All packages from requirements.txt are installed and up to date.
[I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb] | INFO -> loaded 105 nodes successfuly
[I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Eden_Comfy_Pipelines: WARNING: Could not find OPENAI_API_KEY in .env, disabling gpt prompt generation.

    🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱
    🌱 Eden ComfyUI Pack maintained by https://eden.art/  🌱
    🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱

Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[rgthree-comfy] Loaded 42 epic nodes. 🎉

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
FETCH ComfyRegistry Data: 5/82
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 221 nodes successfully.

        "Do one thing every day that scares you." - Eleanor Roosevelt


Import times for custom nodes:
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_pose_inter
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\translate_node.py
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-denoisechooser
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SVGview
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mxtoolkit
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMotionGuider
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-flexi-lora-loader
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\teacachehunyuanvideo
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoMultiLora
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\wywywywy-pause
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-seamless-tiling
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-detail-daemon
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Qwen
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-Hugo
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-ollama
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi-Ollama-YN
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-YOLO
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\save-image-extended-comfyui
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_tag_fillter
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Ib_CustomNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\pose-generator-comfyui-node
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Batch-Condition-ComfyUI
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ResizeAspectratio.py
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-omnigen
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InfiniteYou
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Ollama-Describer
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-cropandstitch
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-filter
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\janus-pro
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\NX_Translator
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-ultralytics-yolo
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Human_Parts
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_yanc
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Saver
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Whisper
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoStyler
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-lama-remover
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ZenID
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Jjk-Nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\image-fitlers
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Yolo-Cropper
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-shinsplat
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-ollama-nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ArtGallery
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantStyle
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-portrait-master
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-eesahesNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfy-WaveSpeed
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_faceanalysis
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TeaCache
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-googletrans
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-lite
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-video-matting
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-model-dynamic-loader
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_patches_ll
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXTricks
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutoCropFaces
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_PoP
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prompt-MZ
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\img2txt-comfyui-nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-RMBG
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BrushNet
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-multigpu
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanLoom
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Flux-Prompt-Generator
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Mira
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UNO
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BrushNet_Wrapper
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\CharacterFaceSwap
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-project
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\lazy-pony-prompter
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Qwen2-VL-Instruct
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_bmad_nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-web-viewer
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MARS5-TTS
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\VocalSeparation-ComfyUI
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_NYJY
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nunchaku
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_dagthomas
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LLaVA-Captioner
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mvadapter
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Mokkaboss1
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX-MZ
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-faster-whisper
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control-legacy
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MiniCPM-V-2_6-int4
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ToSVG
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tensorops
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle_Advance
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\eden_comfy_pipelines
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FluxTrainer
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Captioner
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_HiDream-Sampler
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LogicUtils
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\F5-TTS-ComfyUI
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SVGFullfill
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-advancedliveportrait
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_ryanonyheinside
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MediaMixer
   0.2 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-llm-assistant
   0.2 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\kaytool
   0.2 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic
   0.2 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-itools
   0.2 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX
   0.3 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Allor
   0.3 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OllamaGemini
   0.3 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.3 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.3 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS
   0.3 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ACE_Plus
   0.4 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes
   0.4 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HakuImg
   0.5 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.5 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\abg-comfyui
   0.5 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Bjornulf_custom_nodes
   0.7 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   0.9 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\audio-separation-nodes-comfyui
   0.9 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   1.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ClipInterrogate.py
   1.2 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.2 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_MemoAvatar
   1.4 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-rvc
   1.4 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-disty-Flow

Starting server

To see the GUI go to: http://127.0.0.1:8188
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
FETCH ComfyRegistry Data: 10/82
FETCH ComfyRegistry Data: 15/82
QualityOfLifeSuit_Omar92::NSP ready
[I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb] | INFO -> Found multiple match, we will pick the last E:\SwinIR
['I:\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'E:\\ESRGAN', 'E:\\RealESRGAN', 'E:\\SwinIR']
['anime_lora_comfy_converted.safetensors', 'art_lora_comfy_converted.safetensors', 'disney_lora_comfy_converted.safetensors', 'mjv6_lora_comfy_converted.safetensors', 'realism_lora_comfy_converted.safetensors', 'scenery_lora_comfy_converted.safetensors']
['anime_lora_comfy_converted.safetensors', 'art_lora_comfy_converted.safetensors', 'disney_lora_comfy_converted.safetensors', 'mjv6_lora_comfy_converted.safetensors', 'realism_lora_comfy_converted.safetensors', 'scenery_lora_comfy_converted.safetensors']
FETCH ComfyRegistry Data: 20/82
FETCH ComfyRegistry Data: 25/82
FETCH ComfyRegistry Data: 30/82
FETCH ComfyRegistry Data: 35/82
FETCH ComfyRegistry Data: 40/82
FETCH ComfyRegistry Data: 45/82
FETCH ComfyRegistry Data: 50/82
FETCH ComfyRegistry Data: 55/82
FETCH ComfyRegistry Data: 60/82
FETCH ComfyRegistry Data: 65/82
FETCH ComfyRegistry Data: 70/82
FETCH ComfyRegistry Data: 75/82
FETCH ComfyRegistry Data: 80/82
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by christian-byrne**
Fixes https://github.com/Comfy-Org/ComfyUI_frontend/issues/3539 and Fixes https://github.com/comfyanonymous/ComfyUI/issues/7616 which was caused by a typo in https://github.com/Comfy-Org/ComfyUI_frontend/pull/3302.

https://github.com/Comfy-Org/ComfyUI_frontend/pull/3302 refactored `clientPosToCanvasPos` from

```ts
  clientPosToCanvasPos(pos: Vector2): Vector2 {
    const rect = this.canvasContainer.getBoundingClientRect()
    const containerOffsets = [rect.left, rect.top]
    return _.zip(pos, this.canvas.ds.offset, containerOffsets).map(
      // @ts-expect-error fixme ts strict error
      ([p, o1, o2]) => (p - o2) / this.canvas.ds.scale - o1
    ) as Vector2
  }
```

to

```ts

  const clientPosToCanvasPos = (pos: Vector2): Vector2 => {
    const { offset, scale } = lgCanvas.ds
    return [
      (pos[0] - left.value) / scale + offset[0],
      (pos[1] - top.value) / scale + offset[1]
    ]
  }
```

which adds offset instead of subtracts.

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-3540-Fix-client-canvas-position-conversion-1dc6d73d3650813a9b97dd37fbf5384c) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/composables/useCanvasDrop.ts [hunk 1]
```diff
@@ -29,12 +29,10 @@ export const useCanvasDrop = (canvasRef: Ref<HTMLCanvasElement>) => {
...
           const nodeDef = node.data
-          // Add an offset on x to make sure after adding the node, the cursor
+          const pos = comfyApp.clientPosToCanvasPos([loc.clientX, loc.clientY])
+          // Add an offset on y to make sure after adding the node, the cursor
           // is on the node (top left corner)
-          const pos = comfyApp.clientPosToCanvasPos([
-            loc.clientX,
-            loc.clientY + LiteGraph.NODE_TITLE_HEIGHT
-          ])
+          pos[1] += LiteGraph.NODE_TITLE_HEIGHT
```
Comment (christian-byrne) [inline src/composables/useCanvasDrop.ts:35]: This is not related to the bug or the mentioned PR, but the current calculation is slightly incorrect as it uses NODE_TITLE_HEIGHT logical pixels in argument to `clientPosToCanvasPos` which accepts physical pixels.

The comment was also incorrect as it said `x` instead of `y`.

**Review by webfiltered — APPROVED** [review]

**Comment by webfiltered** [comment]
Just noting: `offset` is _from_ top-left of visible area _to_ canvas 0,0 (all in canvas space).  Which feels unnatural to me, but probably not worth changing.
