### PR TITLE
Fix/widget ordering consistency

### LINKED ISSUE #4983: Node widget values corrupted when input order differs due to JSON key ordering
### Problem Description

When loading workflows, widget values can appear in the wrong positions if the backend returns node inputs in a different order than when the workflow was saved. This occurs because JSON object key ordering is not guaranteed to be preserved (especially in languages like Go), and the frontend doesn't handle this variation correctly.

For example, a KSampler node might have its seed, steps, and cfg values swapped around when loading a workflow, resulting in a seed value appearing where cfg should be, etc.

### Example

Here's how the same KSampler node's inputs can be returned in different orders from different backends:

**Backend A (alphabetical order):**
```json
{
  "cfg": ["FLOAT", { "default": 8, "max": 100, "min": 0, "round": 0.01, "step": 0.1 }],
  "denoise": ["FLOAT", { "default": 1, "max": 1, "min": 0, "step": 0.01 }],
  "latent_image": ["LATENT", {}],
  "model": ["MODEL", {}],
  "negative": ["CONDITIONING", {}],
  "positive": ["CONDITIONING", {}],
  "sampler_name": [["euler", "euler_cfg_pp", "..."], {}],
  "scheduler": [["simple", "sgm_uniform", "..."], {}],
  "seed": ["INT", { "default": 0, "max": 18446744073709552000, "min": 0 }],
  "steps": ["INT", { "default": 20, "max": 10000, "min": 1 }]
}
```

**Backend B (different order):**
```json
{
  "model": ["MODEL", {}],
  "seed": ["INT", { "default": 0, "min": 0, "max": 18446744073709551615 }],
  "steps": ["INT", { "default": 20, "min": 1, "max": 10000 }],
  "cfg": ["FLOAT", { "default": 8.0, "min": 0.0, "max": 100.0, "step": 0.1, "round": 0.01 }],
  "sampler_name": [["euler", "euler_cfg_pp", "..."], {}],
  "scheduler": [["simple", "sgm_uniform", "..."], {}],
  "positive": ["CONDITIONING", {}],
  "negative": ["CONDITIONING", {}],
  "latent_image": ["LATENT", {}],
  "denoise": ["FLOAT", { "default": 1.0, "min": 0.0, "max": 1.0, "step": 0.01 }]
}
```

The widget values in a workflow are stored as an array like this:
```json
{
  "3": {
    "class_type": "KSampler",
    "inputs": { ... },
    "widgets_values": [156680208700286, 1234, "euler", "normal", 20, 8, 1]
  }
}
```

If the widget order changes between save and load, these values get misaligned - the seed value might end up where steps should be, etc.

### Technical Context

- Widget values are serialized as an array indexed by widget position
- The backend provides an `input_order` field in node definitions that specifies the correct order
- The issue relates to how the frontend transforms node definitions and creates widgets from inputs
- This affects the workflow serialization/deserialization process

### Key Areas to Investigate

- How node definitions are transformed when received from the backend
- The widget creation process during node registration
- How widget values are serialized to and deserialized from workflow JSON
- Where and how the `input_order` field could be utilized

### Expected Behavior

- Widget values should maintain their correct associations regardless of JSON key ordering from the backend
- The solution should gracefully handle cases where `input_order` might not exist (backwards compatibility)
- Workflows should be portable between different ComfyUI backends without value corruption

### PR DESCRIPTION
**Pull request by simula-r**
## Summary

Problem: Different backends can serialize node inputs in different orders when sending node definitions. Since the frontend previously created widgets based on the order inputs were positioned in the response, the same node could have widgets in different orders across backends. This breaks workflow compatibility because widgets_values is an array indexed by position.

Solution: Use the input_order field from node definitions to enforce consistent widget ordering across all backends. When input_order is not provided, fall back to the previous behavior for backward compatibility.

## Changes

  1. nodeSchema.ts (src/schemas/nodeDefSchema.ts:241)
    - Added input_order as optional field to track backend-specified ordering
  2. nodeDefStore.ts (src/stores/nodeDefStore.ts:69,137)
    - Store and pass through input_order from backend node definitions
    - Made available in both V1 and V2 formats
  3. nodeDefOrderingUtil.ts (src/utils/nodeDefOrderingUtil.ts)
    - Created getOrderedInputSpecs() to order V2 format inputs according to input_order
    - Handles backward compatibility when input_order is missing
    - Created sortWidgetValuesByInputOrder() for reordering existing widget values
  4. litegraphService.ts (src/services/litegraphService.ts)
    - Updated #addInputs() method to use getOrderedInputSpecs()
    - Ensures widgets are always created in deterministic order
    - Applied to both regular nodes and subgraph nodes
  5. Tests (tests-ui/tests/utils/nodeDefOrderingUtil.test.ts)
    - Comprehensive test coverage including real KSampler node example
    - Tests backward compatibility and edge cases

Fixes: https://github.com/Comfy-Org/ComfyUI_frontend/issues/4983

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-5106-Fix-widget-ordering-consistency-2546d73d3650812687d3c556feaa55cb) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/utils/nodeDefOrderingUtil.ts [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+ * Reorders widget values based on the input_order to match expected widget order.
+ * This is used when widgets were created in a different order than input_order specifies.
+ *
+ * @param widgetValues - The current widget values array
+ * @param currentWidgetOrder - The current order of widget names
+ * @param inputOrder - The desired order from input_order
+ * @returns Reordered widget values array
+ */
+export function sortWidgetValuesByInputOrder(
+  widgetValues: any[],
```
Comment (christian-byrne) [inline src/utils/nodeDefOrderingUtil.ts]: Does it still compile if using `TWidgetValue` in place of all the `any` types?

**Review by christian-byrne — COMMENTED** [review]
Looks good, just one minor question about types

File: src/utils/nodeDefOrderingUtil.ts (hunk 1 above)
Comment (simula-r) [reply src/utils/nodeDefOrderingUtil.ts]: yes indeed, just had to export TWidgetValue from lib/litegraph

Comment (christian-byrne) [reply src/utils/nodeDefOrderingUtil.ts]: @simula-r In that case we may be able to use it for the other `any` in this file as well

Comment (simula-r) [reply src/utils/nodeDefOrderingUtil.ts]: ah yeah i had a straggler, fixed all anys now.

**Review by christian-byrne — APPROVED** [review]
Nice!

Selection_2018
