### PR TITLE
fix: PrimitiveNode combo widget value not persisting in vueNodes mode

### LINKED ISSUE #7694: Nodes v2 - Primitive Nodes Reset on Copy Paste
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [x] I have searched existing issues to make sure this isn't a duplicate
- [x] I have tested with all custom nodes disabled ([see how](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled))

### What happened?

Copying and pasting primitive nodes causes them to reset values

https://github.com/user-attachments/assets/315049f1-6a4a-4089-8362-f5ea1eedd972

### Steps to Reproduce

1.
2.
3.

### How is this affecting you?

Crashes ComfyUI completely

### ComfyUI Frontend Version

v1.36.7

### Browser

Chrome/Chromium

### Console Errors

```javascript

```

### Logs

```shell

```

### Additional Context

_No response_

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-7694-Nodes-v2-Primitive-Nodes-Reset-on-Copy-Paste-2d06d73d365081e4962bde98da1eb9ba) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jtydhr88**
## Summary
- Add missing v-model binding to WidgetWithControl in WidgetSelect.vue
- Trigger callback after setting widget value in PrimitiveNode to update linked widgets

The combo widget value was lost because PrimitiveNode creates combo widgets with controlWidget (via addValueControlWidgets), causing it to use the WidgetWithControl branch which was missing v-model binding.

fix https://github.com/Comfy-Org/ComfyUI_frontend/issues/7694 and https://github.com/Comfy-Org/ComfyUI_frontend/issues/7696

## Screenshots
before
https://github.com/user-attachments/assets/0a0dc668-eb71-4072-b5f7-0c20483fc1ff

after
https://github.com/user-attachments/assets/dfd2274c-8ebf-4105-821a-946063d87e9a

### CODE REVIEW

File: src/extensions/core/widgetInputs.ts [hunk 1]
```diff
@@ -239,6 +239,14 @@ export class PrimitiveNode extends LGraphNode {
...
       if (theirWidget) {
         widget.value = theirWidget.value
+
+        widget.callback?.(
+          widget.value,
+          app.canvas,
+          this,
+          app.canvas?.graph_mouse,
+          {} as CanvasPointerEvent
+        )
```
Comment (AustinMroz) [inline src/extensions/core/widgetInputs.ts]: Is there a place this callback is ever needed? This code section only applies on a newly created widget. Since the code section is synchronous, there's no way for the widget to be initialized in vue prior to callback application.

Comment (jtydhr88) [reply src/extensions/core/widgetInputs.ts]: hm...I think we should keep it.
without it, the input widget connecting primitive node could not display the value we choose in primitive.
image

Comment (jtydhr88) [reply src/extensions/core/widgetInputs.ts]: with it:
image

Comment (AustinMroz) [reply src/extensions/core/widgetInputs.ts]: This code fragment is entirely unrelated to the actual issue and  the difference you observe is likely a consequence of code changes causing a refresh.

I've tracked down the actual issue (`refreshNodeSlots` was reactivity washing) and have opened up a separate PR to fix: #7802

Comment (jtydhr88) [reply src/extensions/core/widgetInputs.ts]: thanks for point it out, removed

**Review by AustinMroz — APPROVED** [review]
