### PR TITLE
fix: reset touch state when iPad Safari loses focus

### LINKED ISSUE #6721: iPadOS 26.1 通过浏览器（Safari、Edge、Google .etc）访问ComfyUI，失去焦点后再返回，一些元素无法交互。
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [x] I have searched existing issues to make sure this isn't a duplicate
- [x] I have tested with all custom nodes disabled ([see how](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled))

### What happened?

测试对象：ComfyUI，无任何其他自定义节点，通过局域网连接，默认设置。

现象：通过Safari、Edge、Google等浏览器访问ComfyUI，切换到其他程序，甚至仅呼出dock栏时，只要浏览器失去焦点，则无法通过单指拖动画布，也无法通过点击两次呼出搜索菜单，无法通过长按右键呼出菜单，只能刷新恢复。

老版本：老版本通过以上测试，甚至额外出现了无法和节点编辑器交互，只能和菜单、文本框交互的现象。

### Steps to Reproduce

1. iPad OS 26.1，Safari浏览器，输入地址192.168.XXX.XXX:8188连接comfyUI，单手指可拖动画布；
2. 手指从底部上滑呼出dock栏，或者切换到其他程序再切换回来；
3. 触摸Safari窗口回到comfyUI，发现单手指无法拖动画布；
4. 由于iPadOS无法降级，无法测试iPadOS老版本表现情况。

### How is this affecting you?

Visual/UI issue only

### ComfyUI Frontend Version

1.32.5

### Browser

Safari

### Console Errors

```javascript
无法收集到log
```

### Logs

```shell
无
```

### Additional Context

iPadOS 26.1

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-6721-iPadOS-26-1-Safari-Edge-Google-etc-ComfyUI-2ae6d73d36508190a2f8edad27b410bc) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jtydhr88**
## Summary
When the browser loses focus (e.g., switching apps, showing the dock), touchend events may not fire, causing touchCount to remain non-zero. This blocks all subsequent single-finger interactions since processMouseDown returns early when touchCount > 0.  

Added visibilitychange and touchcancel event listeners to reset touch state when the page becomes hidden or touch is interrupted by the system.

fix https://github.com/Comfy-Org/ComfyUI_frontend/issues/6721

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-7134-fix-reset-touch-state-when-iPad-Safari-loses-focus-2be6d73d3650819abc7cf9c602909228) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/extensions/core/simpleTouchSupport.ts [hunk 1]
```diff
@@ -82,6 +82,29 @@ app.registerExtension({
...
+    })
+
+    // Also handle touchcancel which fires when touch is interrupted
+    app.canvasEl.parentElement?.addEventListener('touchcancel', () => {
+      touchCount = 0
+      touchZooming = false
+      touchTime = null
+      lastTouch = null
+      lastScale = null
+      touchDist = null
```
Comment (DrJKL) [inline src/extensions/core/simpleTouchSupport.ts]: Since we require the same cleanup, can we extract a method to make sure they stay in sync?

Also, not for this PR, but we might want to find a way to make sure we're cleaning up all the listeners we're adding. It's been a source of memory leaks.

**Review by DrJKL — APPROVED** [review]
