### PR TITLE
[fix] Prevent browser zoom on UI components with canvas wheel event forwarding

### LINKED ISSUE #4568: [Bug]: Canvas menu and selection toolbox capture wheel events causing browser zoom instead of canvas zoom
---
name: Bug Report
about: 'Something is not behaving as expected.'
title: '[Bug]: Canvas menu and selection toolbox capture wheel events causing browser zoom instead of canvas zoom'
labels: ['Potential Bug', 'area:navigation', 'area:ui']
---

### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Frontend Version

v1.25.1

### Expected Behavior

When using the new "Standard" canvas navigation mode (introduced in PR #4533), wheel events with Ctrl held should zoom the canvas consistently regardless of mouse position, including when the mouse is over UI elements like the graph canvas menu (bottom-right) or selection toolbox.

### Actual Behavior

After the canvas navigation mode PR and v1.25.1 release, when accidentally hovering over the graph canvas menu (bottom-right corner) or the selection toolbox (appears when nodes are selected), wheel events with Ctrl held are captured by these UI elements instead of being passed to the canvas. This causes the browser to zoom the entire page instead of zooming the canvas, breaking the expected navigation experience.

### Steps to Reproduce

1. Set canvas navigation mode to "Standard" (default in v1.25.0+) in Settings
2. Open any workflow on the canvas
3. Select one or more nodes to make the selection toolbox appear
4. Hold Ctrl and scroll wheel while mouse cursor is over the selection toolbox
5. Observe that the browser zooms instead of the canvas
6. Alternative: Hold Ctrl and scroll wheel while mouse cursor is over the graph canvas menu (bottom-right corner)
7. Same issue: browser zoom occurs instead of canvas zoom

### Debug Logs

```
[No terminal logs relevant to this frontend issue]
```

### Browser Logs

```
[No console errors - this is a wheel event handling issue]
```

### Setting JSON

```json
{
  "Comfy.Canvas.NavigationMode": "standard"
}
```

### What browsers do you use to access the UI?

- Google Chrome
- Mozilla Firefox

### Other Information

This issue was introduced with the new canvas navigation mode in PR #4533. The problem occurs because:

1. In "Standard" mode, canvas zoom requires Ctrl + wheel events
2. UI components like `GraphCanvasMenu.vue` (positioned at `bottom-[10px] right-[10px]`) and `SelectionToolbox.vue` capture wheel events
3. When these elements have focus or the mouse is over them, the wheel events don't propagate to the canvas
4. The browser interprets Ctrl + wheel as a page zoom command instead

**Affected Components:**
- `src/components/graph/GraphCanvasMenu.vue` - Canvas controls in bottom-right
- `src/components/graph/SelectionToolbox.vue` - Node selection toolbox

**Suggested Fix:**
These components should either:
1. Prevent wheel event capture and allow propagation to the canvas
2. Explicitly forward wheel events to the canvas when Ctrl is held
3. Use `pointer-events: none` for wheel events while maintaining click functionality

This issue significantly impacts the user experience with the new standard navigation mode, as users frequently hover over these UI elements while navigating the canvas.

### PR DESCRIPTION
**Pull request by christian-byrne**
Creates a Vue composable to handle wheel events from UI components and forward them to the canvas when appropriate, preventing unwanted browser zoom. Foundation for migrating canvas interactions to Vue.

Fixes #4568

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-4574-feat-Prevent-browser-zoom-on-UI-components-with-canvas-wheel-event-forwarding-23f6d73d3650816498a6e01828609ef5) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/composables/graph/useCanvasInteractions.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+/**
+ * Composable for handling canvas interactions from Vue components.
+ * This provides a unified way to forward events to the LiteGraph canvas
+ * and will be the foundation for migrating canvas interactions to Vue.
+ */
+export function useCanvasInteractions() {
+  const settingStore = useSettingStore()
+
+  const isStandardNavMode = () =>
+    settingStore.get('Comfy.Canvas.NavigationMode') === 'standard'
```
Comment (christian-byrne) [inline src/composables/graph/useCanvasInteractions.ts]: Make computed value
