### PR TITLE
fix: address small CodeRabbit issues

### LINKED ISSUE #7323: Handle pointercancel and scope disposal in Vue node resize
## Description

The resize implementation in `useNodeResize` currently sets `layoutStore.isResizingVueNodes` to `true` during resize operations and resets it in the `pointerup` handler. However, if the pointer sequence is interrupted (e.g., OS gesture, window blur, device-specific cancel) and `pointerup` never fires, the flag can remain `true`, permanently blocking drag activation until reload.

## Tasks

- Add handling for `pointercancel` event to ensure cleanup happens even when pointer sequences are interrupted
- Add `onScopeDispose` hook to defensively reset the `isResizingVueNodes` flag if the component is unmounted mid-resize
- Ensure `releasePointerCapture` is wrapped in try-catch to handle cases where capture was already released

## Context

Related PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/7064
Original discussion: https://github.com/Comfy-Org/ComfyUI_frontend/pull/7064#discussion_r2575454940
Requested by: @christian-byrne

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-7323-Handle-pointercancel-and-scope-disposal-in-Vue-node-resize-2c56d73d365081d3a892f3bfd85fe362) by [Unito](https://www.unito.io)

### LINKED ISSUE #7955: Refactor: Rename queueIndex to use job.priority directly
## Description

Currently, `queueIndex` is implemented as a getter that returns `job.priority`:

```typescript
get queueIndex() {
  return this.job.priority
}
```

This creates an unnecessary alias. We should refactor the codebase to use `job.priority` (or `task.job.priority`) directly instead of `queueIndex`.

## Context

This issue was identified during the Jobs API migration in PR #7170. The maintainer opted to defer this refactoring to a follow-up PR to keep the migration focused.

## Tasks

- [ ] Search for all usages of `queueIndex` in the codebase
- [ ] Replace with direct `job.priority` access
- [ ] Remove the `queueIndex` getter from `TaskItemImpl`
- [ ] Update tests accordingly

## References

- PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/7170
- Discussion: https://github.com/Comfy-Org/ComfyUI_frontend/pull/7170#discussion_r2651881412
- Requested by: @christian-byrne

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-7955-Refactor-Rename-queueIndex-to-use-job-priority-directly-2e56d73d36508185b059dd07095bd477) by [Unito](https://www.unito.io)

### LINKED ISSUE #8703: Parameterize repetitive test cases in modelToNodeStore.test.ts
## Context
Identified during review of PR #8468: https://github.com/Comfy-Org/ComfyUI_frontend/pull/8468
Comment: https://github.com/Comfy-Org/ComfyUI_frontend/pull/8468#discussion_r2776248903

## Description
Several test cases in `src/stores/modelToNodeStore.test.ts` follow similar patterns and could be parameterized using Vitest's `it.each()` or similar approaches to reduce code duplication and improve maintainability.

## Test Cases to Parameterize

The following tests in the `getNodeProvider` describe block have similar structures:

1. **"should return provider for new extension model types"** - tests multiple model types (sam2, sams, ipadapter, depthanything) with assertions on nodeDef name and key
2. **"should use hierarchical fallback for ultralytics subcategories"** - tests ultralytics/bbox and ultralytics/segm
3. **"should return provider for FlashVSR nodes with empty key (auto-load)"** - tests FlashVSR and FlashVSR-v1.1
4. **"should return provider for segformer models"** - tests segformer_b2_clothes and segformer_b3_fashion

## Suggested Approach

Use Vitest's `it.each()` to create a test table with columns for:
- Model type
- Expected node definition name
- Expected key value

Example pattern:
```typescript
it.each([
  ['sam2', 'DownloadAndLoadSAM2Model', 'model'],
  ['sams', 'SAMLoader', 'model_name'],
  ['ipadapter', 'IPAdapterModelLoader', 'ipadapter_file'],
  // ... more test cases
])('should return provider for %s model type', (modelType, expectedNodeName, expectedKey) => {
  const modelToNodeStore = useModelToNodeStore()
  modelToNodeStore.registerDefaults()
  
  const provider = modelToNodeStore.getNodeProvider(modelType)
  expect(provider?.nodeDef?.name).toBe(expectedNodeName)
  expect(provider?.key).toBe(expectedKey)
})
```

## Benefits
- Reduces code duplication
- Makes it easier to add new test cases
- Improves test maintainability
- Clearer test structure

---
Requested by: @DrJKL

### LINKED ISSUE #9024: Replace custom useCopyToClipboard with VueUse useClipboard
## Description

Replace our custom `useCopyToClipboard` composable with VueUse's [`useClipboard`](https://vueuse.org/core/useClipboard/) to leverage the established library and reduce maintenance burden.

## Current State
- We maintain a custom `useCopyToClipboard` composable at `src/composables/useCopyToClipboard.ts`
- It's currently used in various components including the new MissingModelsContent component

## Proposed Change
Replace all usages of our custom composable with VueUse's `useClipboard`, which provides:
- Clipboard write/read functionality
- Copy status and error handling
- Legacy browser support
- TypeScript support

## Related
- Requested by: @DrJKL
- PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/9014
- Comment: https://github.com/Comfy-Org/ComfyUI_frontend/pull/9014#discussion_r2835181102

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-9024-Replace-custom-useCopyToClipboard-with-VueUse-useClipboard-30d6d73d36508108a2d8cea9ce1b2e34) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by Myestery**
## Summary

Address several small CodeRabbit-filed issues: clipboard simplification, queue getter cleanup, pointer handling, and test parameterization.

## Changes

- **What**:
  - Simplify `useCopyToClipboard` by using VueUse's built-in `legacy` mode instead of a manual `document.execCommand` fallback
  - Remove `queueIndex` getter alias from `TaskItemImpl`, replace all usages with `job.priority`
  - Add `pointercancel` event handling and try-catch around `releasePointerCapture` in `useNodeResize` to prevent stuck resize state
  - Parameterize repetitive `getNodeProvider` tests in `modelToNodeStore.test.ts` using `it.each()`

- Fixes #9024
- Fixes #7955
- Fixes #7323
- Fixes #8703

## Review Focus

- `useCopyToClipboard`: VueUse's `legacy: true` enables the `execCommand` fallback internally — verify browser compat is acceptable
- `useNodeResize`: cleanup logic extracted into shared function used by both `pointerup` and `pointercancel`

### CODE REVIEW

File: src/stores/queueStore.ts [hunk 1]
```diff
@@ -500,7 +496,7 @@ export const useQueueStore = defineStore('queue', () => {
   )
 
   const lastHistoryQueueIndex = computed<number>(() =>
```
Comment (christian-byrne) [inline src/stores/queueStore.ts:498]: nitpick (non-blocking): the computed is now reading `job.priority` but the variable is still named `lastHistoryQueueIndex`. consider renaming to `lastHistoryJobPriority` (or similar) for consistency with the getter removal. same applies to `currentQueueIndex` in JobDetailsPopover.vue.

@coderabbitai Make an Issue to do this in a followup PR on a future date

**Review by christian-byrne — APPROVED** [review]
