### PR TITLE
[fix] Detect missing nodes in subgraphs

### LINKED ISSUE #4618: [Bug] When there is a missing node inside the subgraph, there will be no missing node promo
https://github.com/user-attachments/assets/237b7d99-ae9b-439c-8f03-77ab5cccf0c8

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-4618-Bug-When-there-is-a-missing-node-in-the-subgraph-there-will-be-no-missing-node-prom-2416d73d36508103beeac6c614e1f6ea) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by viva-jinyi**
## Summary
This PR fixes an issue where missing nodes inside subgraphs were not being detected and reported to users. The missing node warning dialog would only appear for missing nodes at the top level of the workflow, but not for nodes within subgraphs.

## Changes
- Modified `loadGraphData` in `app.ts` to recursively check nodes in subgraphs for missing node types
- Added context to missing node error messages showing the subgraph location (e.g., "MISSING_NODE (in subgraph 'MySubgraph')")
- Created test workflow `missing_nodes_in_subgraph.json` with a missing node inside a subgraph
- Added Playwright test to verify the warning appears for missing nodes in subgraphs

## Testing
- Created new Playwright test that verifies missing nodes in subgraphs are detected
- All existing tests pass
- Manual testing confirms the warning dialog now shows missing nodes from subgraphs with proper context

## Related Issues
Fixes #4618

## Screenshots
[screen-capture.webm](https://github.com/user-attachments/assets/494ae0d4-edd9-4f36-b2c0-03612a6490ba)

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-4639-fix-Detect-missing-nodes-in-subgraphs-2426d73d36508160ac5ce8cb558fcb01) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/scripts/app.ts [hunk 1]
```diff
@@ -1092,23 +1092,42 @@ export class ComfyApp {
...
+          n.type = 'SVD_img2vid_Conditioning' //typo fix
+
+        // Find missing node types
+        if (!(n.type in LiteGraph.registered_node_types)) {
+          // Include context about subgraph location if applicable
+          const nodeTypeWithContext = path
+            ? `${n.type} (in subgraph '${path}')`
+            : n.type
+          missingNodeTypes.push(nodeTypeWithContext)
+          n.type = sanitizeNodeName(n.type)
```
Comment (christian-byrne) [inline src/scripts/app.ts]: For the missingNodeTypes, it is a union type:

https://github.com/Comfy-Org/ComfyUI_frontend/blob/47e18088611f905588deb6912524ea233daab491/src/types/comfy.ts#L33-L43

It might be better to not modify the `type` and instead use the secondary format like

```ts
missingNodeTypes.push({
  type: n.type
  hint: nodeTypeWithContext
})
```

or something similar.

The type of missingNodeTypes is defined in the public API for extension lifecycle hook `beforeConfigureGraphData` so there is an added obligation to adhere to it.

File: src/scripts/app.ts [hunk 2]
```diff
@@ -1092,23 +1092,42 @@ export class ComfyApp {
...
+    processNodesRecursively(graphData.nodes)
 
-      // Collect models metadata from node
-      const selectedModels = getSelectedModelsMetadata(n)
-      if (selectedModels?.length) {
-        embeddedModels.push(...selectedModels)
+    // Process nodes in subgraphs
+    if (graphData.definitions?.subgraphs) {
+      for (const subgraph of graphData.definitions.subgraphs as any[]) {
+        if (subgraph.nodes) {
```
Comment (christian-byrne) [inline src/scripts/app.ts]: it seems like `nodes` is not defined on `graphData.definitions.subgraphs` in the schema https://github.com/Comfy-Org/ComfyUI_frontend/blob/main/src/schemas/comfyWorkflowSchema.ts

But in the actual serialized workflows, the `nodes` property exists. I think this might be a mistake in the schema.

Comment (christian-byrne) [reply src/scripts/app.ts:1128]: Looking into it now

Comment (christian-byrne) [reply src/scripts/app.ts]: I found the issue: https://github.com/Comfy-Org/ComfyUI_frontend/issues/4650.

File: src/scripts/app.ts (hunk 1 above)
Comment (viva-jinyi) [reply src/scripts/app.ts]: Thank you for the review! I've updated the code to use the proper MissingNodeType format as you suggested.

File: src/scripts/app.ts (hunk 2 above)
Comment (viva-jinyi) [reply src/scripts/app.ts]: Removed the as any[] cast - replaced with a defensive type guard 'nodes' in subgraph &&  Array.isArray(subgraph.nodes) to ensure type safety

Comment (christian-byrne) [reply src/scripts/app.ts]: I am adding a typeguard to use so we don't need to cast to `any`: https://github.com/Comfy-Org/ComfyUI_frontend/pull/4651

File: src/scripts/app.ts [hunk 3]
```diff
@@ -1092,23 +1092,47 @@ export class ComfyApp {
...
 
-      // Collect models metadata from node
-      const selectedModels = getSelectedModelsMetadata(n)
-      if (selectedModels?.length) {
-        embeddedModels.push(...selectedModels)
+    // Process nodes at the top level
+    processNodesRecursively(graphData.nodes)
+
+    // Process nodes in subgraphs
+    if (graphData.definitions?.subgraphs) {
```
Comment (christian-byrne) [inline src/scripts/app.ts:1133]: Can you use this typeguard so that we don't need to use `any` in line 1096?

https://github.com/Comfy-Org/ComfyUI_frontend/blob/61c9341450f56f892cc7673b33de8a1fb799df3e/src/schemas/comfyWorkflowSchema.ts#L463-L478

This will cast to the correct type. It is necessary because of zod `lazy` on circular subgraph schema.

Comment (christian-byrne) [reply src/scripts/app.ts:1133]: I'll take care of this so we can release subgraphs quickly

**Review by christian-byrne — APPROVED** [review]
LGTM thanks for adding browser test
