### PR TITLE
Fix keybinds invalidated by capslock state

### LINKED ISSUE #1315: [Bug]: Capslock breaks keyboard shortcuts
### Frontend Version

1.2.23

### Expected Behavior

Capslock does not impact keyboard shortcuts.

### Actual Behavior

Creating a `ctrl + b` shortcut:
- Capslock on: `ctrl + B`
- Capslock off: `ctrl + b`

`ctrl + b` shortcut does not work with capslock on, and vice-versa.

`ctrl + B` is not triggered by `ctrl + shift + b`, and vice-versa-capslock.

### Steps to Reproduce

Press capslock.  Make bindings.  Woe.

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

### What browsers do you use to access the UI ?

Google Chrome

### Other

_No response_

### PR DESCRIPTION
**Pull request by webfiltered**
### User changes

- Keybinds now always serialise in upper case
- Fixes `changeTracker` behaviour inverted by capslock (ctrl / ctrl + shift + z)
- If two keybinds for the same key exist (e.g. `Ctrl` + `e`, and `Ctrl` + `E`), one will need to be rebound - it will not show up in GUI
  - This can probably be fixed, but would require larger changes
  - A script to detect and delete duplicate binds, then notify the user would be easier

#### Notes

- Removes `KeyComboImpl.deserialize` method (unused?)
- Adds compile-time type safety to some explicit-any methods
- Individual commits should be easy to revert if desired
- Resolves #1315

### CODE REVIEW

**Review by huchenlei — APPROVED** [review]

File: src/stores/keybindingStore.ts [hunk 1]
```diff
@@ -51,30 +50,19 @@ export class KeyComboImpl implements KeyCombo {
...
-    }
-    return false
-  }
+  equals(other: unknown): boolean {
+    const raw = toRaw(other)
 
-  serialize(): string {
-    return `${this.key}:${this.ctrl}:${this.alt}:${this.shift}`
+    return raw instanceof KeyComboImpl
+      ? this.key.toUpperCase() === raw.key.toUpperCase() &&
```
Comment (huchenlei) [inline src/stores/keybindingStore.ts:57]: Special note: this line keeps backward compatibility with existing keybindings user saved. The existing keybindings will not be migrated to upper case format.
