### PR TITLE
refactor: extract shouldUseAssetBrowser(), fix missing inputNameForBrowser, sanitize logs

### LINKED ISSUE #8744: Refactor PrimitiveNode asset widget code after PR #8594 merges
## Background

This is a follow-up refactoring task for the asset widget support added in PR #8598.

## Task

After PR #8594 is merged, review and refactor the PrimitiveNode asset widget code (specifically in `src/extensions/core/widgetInputs.ts` and related files) to simplify it if possible.

## Dependencies

- Blocked by: #8594
- Original implementation: #8598

## Context

Requested by @christian-byrne in https://github.com/Comfy-Org/ComfyUI_frontend/pull/8598

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-8744-Refactor-PrimitiveNode-asset-widget-code-after-PR-8594-merges-3016d73d3650817cbc98dfb5fbd86dac) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by christian-byrne**
## Summary

Extract duplicated asset-browser eligibility guard into `shouldUseAssetBrowser()`, fix a missing parameter bug, and sanitize a log statement.

## Changes

- **What**: 
  - DRY: Extract the repeated 3-condition guard (`isCloud && isUsingAssetAPI && isAssetBrowserEligible`) into `assetService.shouldUseAssetBrowser()`, used by `widgetInputs.ts` and `useComboWidget.ts`
  - Bug fix: `createAssetBrowserWidget()` in `useComboWidget.ts` was missing the `inputNameForBrowser` parameter, which could show wrong assets for nodes with multiple model inputs
  - Security: `createAssetWidget.ts` no longer logs the full raw asset object on validation failure
  - `WidgetSelect.vue` keeps an inline guard because it has a special `widget.type === "asset"` fallback that must stay gated behind `isUsingAssetAPI`

## Review Focus

- `shouldUseAssetBrowser()` correctly combines the three conditions that were previously duplicated
- `WidgetSelect.vue` preserves exact behavioral equivalence (a widget can have `type === "asset"` when the setting is off if a user toggles the setting after creating asset widgets)

Fixes #8744

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-8867-refactor-extract-shouldUseAssetBrowser-fix-missing-inputNameForBrowser-sanitize-logs-3076d73d3650818cabdcd76a351dac31) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/extensions/core/widgetInputs.ts [hunk 1]
```diff
@@ -233,21 +231,15 @@ export class PrimitiveNode extends LGraphNode {
...
-      }
+    if (
+      type === 'COMBO' &&
+      assetService.shouldUseAssetBrowser(node.comfyClass, widgetName)
+    ) {
+      widget = this._createAssetWidget(node, widgetName, inputData)
+      const theirWidget = node.widgets?.find((w) => w.name === widgetName)
+      if (theirWidget) widget.value = theirWidget.value
+      this._finalizeWidget(widget, oldWidth, oldHeight, recreating)
+      return
```
Comment (DrJKL) [inline src/extensions/core/widgetInputs.ts:242]: I hate the primitive node so much...
I still use it a lot, but I hate it and want to destroy it at the same time.

File: src/renderer/extensions/vueNodes/widgets/components/WidgetSelect.vue [hunk 2]
```diff
@@ -112,17 +112,12 @@ const specDescriptor = computed<{
...
-    return isUsingAssetAPI && isEligible
-  }
-
-  return false
+  if (!isCloud) return false
+  if (!useSettingStore().get('Comfy.Assets.UseAssetAPI')) return false
+  return (
+    assetService.isAssetBrowserEligible(props.nodeType, props.widget.name) ||
+    props.widget.type === 'asset'
+  )
```
Comment (DrJKL) [inline src/renderer/extensions/vueNodes/widgets/components/WidgetSelect.vue]: This is so close to shouldUseAssetBrowser...

**Review by DrJKL — DISMISSED** [review]

File: src/extensions/core/widgetInputs.ts (hunk 1 above)
Comment (christian-byrne) [reply src/extensions/core/widgetInputs.ts:242]: Agreed
