### PR TITLE
fix: store promoted widget values per SubgraphNode instance

### LINKED ISSUE #10146: [Regression] Loading a workflow from an image sets incorrect subgraph parameters
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [ ] I have custom nodes enabled

### What happened?

With the recent frontend bump past v1.39.19 workflows stored in older images started producing different results.

### Steps to Reproduce

Image

1. Load the workflow in the above test image in latest ComfyUI. I believe there aren't even any custom nodes here.
2. Generate the workflow.
3. You will get a different image:

Image

This seems to be caused by subgraph parameters being loaded incorrectly - in the source image the 3 subgraphs have different parameters. If loaded in a newer version the parameters are all incorrectly the same.

### How is this affecting you?

Feature doesn't work as expected

### ComfyUI Frontend Version

v1.43.1

### Browser

Chrome/Chromium

### Console Errors

```javascript

```

### Logs

```shell

```

### Additional Context

Tested the following versions before getting rate limited:

v1.43.1 - broken
v1.42.8 - broken
v1.41.20 - broken
v1.41.3 - works fine
v1.40.0 - works fine
v1.39.19 - works fine

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-10146-Loading-a-workflow-from-an-image-now-produces-a-different-image-3266d73d36508142a98fc21e1d606934) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by dante01yoon**
## Summary

- Multiple SubgraphNode instances of the same blueprint share inner nodes, causing promoted widget values to collide — the last configured instance overwrites all previous values
- Add per-instance value storage (`_instanceWidgetValues`) on SubgraphNode so each instance preserves its own promoted widget values independently
- Restore `widgets_values` from serialized data into this per-instance map after promoted views are created during configure

- Fixes #10146

## Root Cause

When loading a workflow with multiple SubgraphNode instances of the same blueprint:

1. `LGraph.configure()` creates ONE shared Subgraph per blueprint (line 2625)
2. Each SubgraphNode instance calls `configure(instanceData)` sequentially
3. `PromotedWidgetView.value` setter writes to the **shared inner node's widget** (`promotedWidgetView.ts:199`)
4. The last instance's `configure()` overwrites all previous instances' values

**Regression**: Introduced by PR #8594 (WidgetValueStore, v1.41.3) which centralized widget state without per-instance scoping for shared blueprints.

## Fix

- **SubgraphNode**: Add `_instanceWidgetValues` Map and `_pendingWidgetsValues` for configure-time restoration
- **PromotedWidgetView getter**: Check instance map first before falling back to widget store / inner node
- **PromotedWidgetView setter**: Write to instance map to avoid shared inner node mutation
- **_internalConfigureAfterSlots**: Apply serialized `widgets_values` to per-instance map after promoted views are created

## Red-Green Verification

| Commit | CI Status | Purpose |
|--------|-----------|---------|
| `test: add failing tests for multi-instance subgraph widget value collision` | :red_circle: Red | Proves widget values collide across instances |
| `fix: store promoted widget values per SubgraphNode instance` | :green_circle: Green | Per-instance storage prevents collision |

## Test Plan

- [x] CI red on test-only commit
- [x] CI green on fix commit
- [x] Unit test: `preserves promoted widget values after configure with different widgets_values`
- [x] All 253 existing subgraph tests pass
- [ ] Manual: load workflow from issue image → verify 3 subgraph instances produce different results

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-10849-fix-store-promoted-widget-values-per-SubgraphNode-instance-3386d73d3650815a8544f54adcc0d504) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/core/graph/subgraph/promotedWidgetView.ts [hunk 1]
```diff
@@ -149,13 +149,30 @@ class PromotedWidgetView implements IPromotedWidgetView {
...
+
   get value(): IBaseWidget['value'] {
+    // Check per-instance values first (populated during configure for
+    // multi-instance subgraphs sharing the same blueprint).
+    const instanceValue = this.subgraphNode._instanceWidgetValues.get(
+      this._instanceKey
+    )
+    if (instanceValue !== undefined)
+      return instanceValue as IBaseWidget['value']
+
```
[the remark this answers is not in the document]
Comment (dante01yoon) [reply src/core/graph/subgraph/promotedWidgetView.ts]: addressed

**Comment by dante01yoon** [comment]
@coderabbitai approve

**Comment by benceruleanlu** [comment]
Taking a look now

File: src/lib/litegraph/src/subgraph/SubgraphNode.multiInstance.test.ts [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+      widgets_values: [20]
+    })
+
+    // After configuring both, each instance's per-instance value
+    // should be preserved in _instanceWidgetValues, even though the
+    // shared inner widget holds the last-configured value.
+    expect(instance1._instanceWidgetValues.size).toBeGreaterThan(0)
+    expect(instance2._instanceWidgetValues.size).toBeGreaterThan(0)
+    expect([...instance1._instanceWidgetValues.values()]).toContain(10)
+    expect([...instance2._instanceWidgetValues.values()]).toContain(20)
```
Comment (benceruleanlu) [inline src/lib/litegraph/src/subgraph/SubgraphNode.multiInstance.test.ts]: The red/green/regression test, while indeed is a unit test I feel like could use a little more higher level user centric code or at least the actually used methods than expecting a private field, which would've caught the other mentioned issue

File: src/core/graph/subgraph/promotedWidgetView.ts [hunk 3]
```diff
@@ -149,13 +149,32 @@ class PromotedWidgetView implements IPromotedWidgetView {
...
 
+  /**
+   * Read the per-instance value stored during configure.
+   * Used by graphToPrompt to get the correct execution value when
+   * multiple SubgraphNode instances share the same blueprint.
+   */
+  getInstanceValue(): IBaseWidget['value'] | undefined {
+    const v = this.subgraphNode._instanceWidgetValues.get(this._instanceKey)
+    return v as IBaseWidget['value'] | undefined
+  }
```
Comment (benceruleanlu) [inline src/core/graph/subgraph/promotedWidgetView.ts:228]: getInstanceValue() has no callers.

**Review by benceruleanlu — CHANGES_REQUESTED** [review]
The added _instanceWidgetValues doesn't seem to be used by any production read path.

File: src/core/graph/subgraph/promotedWidgetView.ts (hunk 3 above)
Comment (dante01yoon) [reply src/core/graph/subgraph/promotedWidgetView.ts:228]: Good catch — removed `getInstanceValue()` entirely. The per-instance lookup is now wired directly into the `value` getter (before the shared widget state store fallback), which is the actual read path used by `executionUtil` and `ExecutableNodeDTO`. This also revealed that the lookup needed to come *before* `getWidgetState()`, since the widget state store is keyed by inner node ID and returns the last-configured value for all instances.

File: src/lib/litegraph/src/subgraph/SubgraphNode.multiInstance.test.ts (hunk 2 above)
Comment (dante01yoon) [reply src/lib/litegraph/src/subgraph/SubgraphNode.multiInstance.test.ts]: Agreed — rewrote the test to assert through the public `widgets[0].value` getter instead of inspecting `_instanceWidgetValues` directly. This immediately caught the real bug: the getter wasn't checking the per-instance map, so both instances returned 20 (the last-configured value from the shared state).

**Review by benceruleanlu — DISMISSED** [review]

File: src/lib/litegraph/src/subgraph/SubgraphNode.ts [hunk 4]
```diff
@@ -993,7 +993,20 @@ export class SubgraphNode extends LGraphNode implements BaseLGraph {
...
+  /**
+   * Per-instance promoted widget values.
+   * Multiple SubgraphNode instances share the same inner nodes, so
+   * promoted widget values must be stored per-instance to avoid collisions.
+   * Key: `${sourceNodeId}:${sourceWidgetName}`
+   */
+  readonly _instanceWidgetValues = new Map<string, unknown>()
+
   override configure(info: ExportedSubgraphInstance): void {
+    this._pendingWidgetsValues = info.widgets_values
```
Comment (benceruleanlu) [inline src/lib/litegraph/src/subgraph/SubgraphNode.ts:1009]: `_instanceWidgetValues` is only hydrated from saved `widgets_values` here. Fresh instances still fall back to shared inner-widget state, so edits can leak between instances until after save/reload.

File: src/lib/litegraph/src/subgraph/SubgraphNode.ts [hunk 5]
```diff
@@ -1573,36 +1600,29 @@ export class SubgraphNode extends LGraphNode implements BaseLGraph {
...
       this.id
     )
     this.properties.proxyWidgets = this._serializeEntries(entries)
 
-    return super.serialize()
+    const serialized = super.serialize()
+    const views = this._getPromotedViews()
+
+    if (views.length > 0) {
+      serialized.widgets_values = views.map((view) => {
```
Comment (benceruleanlu) [inline src/lib/litegraph/src/subgraph/SubgraphNode.ts]: Should this only serialize promoted widgets whose source widget is workflow-persistent? This now saves preview/audio/video widgets even when the source widget sets `serialize = false`.

**Review by benceruleanlu — COMMENTED** [review]
Maybe we should add a test case for this?

1. Create two instances of the same subgraph.
2. Edit a promoted widget on instance A.
3. Instance A stores its own value, but it also updates the shared inner widget/store.
4. Instance B has no per-instance entry yet, so its getter falls back to that shared state.
5. Instance B now shows or executes with A’s value.

**Comment by benceruleanlu** [comment]
Can go in if the serialization concern is either intended or doesn't matter, since this PR does fix the save/load path, just not the in memory path

File: src/lib/litegraph/src/subgraph/SubgraphNode.ts (hunk 5 above)
Comment (dante01yoon) [reply src/lib/litegraph/src/subgraph/SubgraphNode.ts]: Fixed in 3a83180. Added `sourceSerialize` getter on `PromotedWidgetView` that checks `resolveDeepest()?.widget.serialize !== false`. Both `serialize()` and the configure restore path now filter with it, so non-persistent source widgets (preview/audio/video) are skipped symmetrically.

File: src/lib/litegraph/src/subgraph/SubgraphNode.ts (hunk 4 above)
Comment (dante01yoon) [reply src/lib/litegraph/src/subgraph/SubgraphNode.ts:1009]: Valid concern. The value getter falls through to shared inner-widget state (widget state store and `resolveAtHost().widget.value`), and the setter writes to both `_instanceWidgetValues` AND those shared sinks. For fresh instances that were never explicitly set, the getter picks up values written by sibling instances.

I investigated three approaches:
1. **Seed `_instanceWidgetValues` at creation** — breaks nested subgraph propagation (`comboWidget.value = 'b'` test) because the seed shadows direct inner widget changes
2. **Remove shared state writes from setter** — breaks 12 tests (linked widget cascading, three-level nested propagation, rendering sync)
3. **Skip widget state store in getter** — the setter also writes to `resolveAtHost().widget.value`, so the fallback still gets polluted

The root cause is architectural: the getter can't distinguish "value set by sibling instance's setter" from "value set by direct inner widget edit". A proper fix needs either an observer on inner widgets to keep `_instanceWidgetValues` in sync, or making the per-instance map the sole source of truth with shared state syncing as a separate concern. Both are beyond this PR's scope.

Note: `serializeValue` (used by graphToPrompt) falls through to `this.value`, so execution is also affected for fresh instances. Filing a follow-up for this.

**Review by benceruleanlu — DISMISSED** [review]
can't wait for the ECS refactor.

**Comment by dante01yoon** [comment]
Follow-up fix is in #11011.

I verified three side effects against `#10849` head and addressed them there:
- fresh sibling instances leaking promoted widget values before save/reload
- restored promoted widgets not reflecting later direct inner-widget edits
- stale per-instance values surviving reconfigure paths without `widgets_values`

Validation for the follow-up is in #11011.

**Review by benceruleanlu — APPROVED** [review]
Going off of my last two reviews
