### PR TITLE
fix: spin out workflow tab/load stability regressions

### LINKED ISSUE #9320: User workflow data becomes disordered after opening a new workflow.
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [ ] I have custom nodes enabled

### What happened?

When I updated comfyui-frontend-package==1.38.13 to comfyui-frontend-package==1.38.14, opening a new workflow in the workflow panel after opening a workflow on the front-end page would overwrite the data of the currently opened workflow, resulting in the loss of the user's workflow. The only way to undo this was by pressing Ctrl+Z. As a result, I had no choice but to leave the front-end code at version 1.38.13. This problem exists in all versions after that.

### Steps to Reproduce

1.open a exist workflow.

Image**Example of use version==1.38.13, the problem occurred version>=1.38.14**

2.open the workflow panel and open another exist workflow.

Image**Example of use version==1.38.13, the problem occurred version>=1.38.14**

3.the first workflow modified to the second workflow. 

ps: This completely modified the JSON of all my local workflows.This is a really bad bug.

### How is this affecting you?

Crashes ComfyUI completely

### ComfyUI Frontend Version

&gt;=1.38.14

### Browser

Chrome/Chromium

### Console Errors

```javascript

```

### Logs

```shell

```

### Additional Context

_No response_

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-9320-User-workflow-data-becomes-disordered-after-opening-a-new-workflow-3166d73d36508134b553d5c5a9031bc5) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by DrJKL**
## Summary

Spin out workflow tab/load stability fixes from the share-by-url branch so they can merge independently and reduce regression risk.

## Changes

- **What**: Fixes duplicate tabs on repeated same-workflow loads by making active-workflow reload idempotent in `afterLoadNewGraph`; fixes tab flicker on save/rename by removing async detach/attach gaps in `workflowStore`; hardens duplicate workflow path by loading before clone and assigning a new workflow `id`.

## Review Focus

Please review the idempotency gate in `afterLoadNewGraph` (`activeState.id === workflowData.id`) and the save/rename path update sequencing in `workflowStore` to confirm behavior remains correct for restoration and re-import flows.

## Screenshots (if applicable)

N/A (workflow logic and tests only)

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-9345-fix-spin-out-workflow-tab-load-stability-regressions-3186d73d365081fe922bdc61dcf8d8f8) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/platform/workflow/management/stores/workflowStore.ts [hunk 1]
```diff
@@ -479,12 +479,15 @@ export const useWorkflowStore = defineStore('workflow', () => {
...
+      await workflow.rename(newPath)
+
+      // Synchronously swap old path for new path in lookup and open paths
+      // to avoid a tab flicker caused by an async gap between detach/attach.
+      delete workflowLookup.value[oldPath]
+      workflowLookup.value[workflow.path] = workflow
+      const openIndex = openWorkflowPaths.value.indexOf(oldPath)
+      if (openIndex !== -1) {
+        openWorkflowPaths.value.splice(openIndex, 1, workflow.path)
       }
```
[the remark this answers is not in the document]
Comment (DrJKL) [reply src/platform/workflow/management/stores/workflowStore.ts:491]: We shouldn't have multiple instances with the same path.

File: src/platform/workflow/core/services/workflowService.test.ts [hunk 2]
```diff
@@ -307,6 +307,56 @@ describe('useWorkflowService', () => {
...
+      expect(workflowStore.openWorkflow).toHaveBeenCalledWith(existingWorkflow)
+      expect(existingWorkflow.changeTracker.reset).toHaveBeenCalled()
+      expect(existingWorkflow.changeTracker.restore).toHaveBeenCalled()
+      expect(workflowStore.createNewTemporary).not.toHaveBeenCalled()
+    })
+
+    it('should reuse active workflow for repeated same-path loads without ids', async () => {
+      await useWorkflowService().afterLoadNewGraph('repeat', {
+        nodes: [{ id: 1, type: 'TestNode', pos: [0, 0], size: [100, 100] }]
+      } as never)
```
Comment (pythongosssss) [inline src/platform/workflow/core/services/workflowService.test.ts]: bypassing typechecks

File: src/platform/workflow/core/services/workflowService.ts [hunk 3]
```diff
@@ -389,10 +389,30 @@ export const useWorkflowService = () => {
...
+          !!existingWorkflow &&
+          workflowStore.isActive(existingWorkflow) &&
+          existingWorkflow.activeState?.id === undefined &&
+          workflowData.id === undefined
+
+        if (
+          existingWorkflow &&
+          ((existingWorkflow.isPersisted && !existingWorkflow.isLoaded) ||
+            isSameActiveWorkflowLoad ||
+            isSameActiveWorkflowLoadWithoutIds)
```
Comment (Yourz) [inline src/platform/workflow/core/services/workflowService.ts]: `isSameActiveWorkflowLoad || isSameActiveWorkflowLoadWithoutIds` could be merge as

```
!!existingWorkflow &&
  workflowStore.isActive(existingWorkflow) &&
  existingWorkflow.activeState?.id === workflowData.id
```

**Review by christian-byrne — DISMISSED** [review]

File: src/platform/workflow/core/services/workflowService.ts [hunk 4]
```diff
@@ -389,10 +389,30 @@ export const useWorkflowService = () => {
...
+          !!existingWorkflow &&
+          workflowStore.isActive(existingWorkflow) &&
+          existingWorkflow.activeState?.id !== undefined &&
+          workflowData.id !== undefined &&
+          existingWorkflow.activeState.id === workflowData.id
+        const isSameActiveWorkflowLoadWithoutIds =
+          !!existingWorkflow &&
+          workflowStore.isActive(existingWorkflow) &&
+          existingWorkflow.activeState?.id === undefined &&
+          workflowData.id === undefined
```
Comment (christian-byrne) [inline src/platform/workflow/core/services/workflowService.ts]: issue: The idempotency gate has a gap when one side has an `id` and the other doesn't. If `existingWorkflow.activeState?.id` is defined but `workflowData.id` is `undefined` (or vice versa), neither `isSameActiveWorkflowLoad` nor `isSameActiveWorkflowLoadWithoutIds` is true, so the code falls through to `createNewTemporary` and opens a duplicate tab for the same path.

A single predicate would eliminate both the duplication and the gap:
```ts
const isSameActiveWorkflowLoad =
  !!existingWorkflow &&
  workflowStore.isActive(existingWorkflow) &&
  (existingWorkflow.activeState?.id === undefined ||
   workflowData.id === undefined ||
   existingWorkflow.activeState.id === workflowData.id)
```

File: src/platform/workflow/management/stores/workflowStore.ts [hunk 5]
```diff
@@ -479,12 +479,15 @@ export const useWorkflowStore = defineStore('workflow', () => {
...
-        attachWorkflow(workflow, openIndex)
+      await workflow.rename(newPath)
+
+      // Synchronously swap old path for new path in lookup and open paths
+      // to avoid a tab flicker caused by an async gap between detach/attach.
+      delete workflowLookup.value[oldPath]
+      workflowLookup.value[workflow.path] = workflow
+      const openIndex = openWorkflowPaths.value.indexOf(oldPath)
+      if (openIndex !== -1) {
+        openWorkflowPaths.value.splice(openIndex, 1, workflow.path)
```
Comment (christian-byrne) [inline src/platform/workflow/management/stores/workflowStore.ts:490]: suggestion (non-blocking): The rename now manually manipulates `workflowLookup` and `openWorkflowPaths` inline instead of using the existing `detachWorkflow`/`attachWorkflow` helpers. This creates a second mutation path for the same data structures, so future changes to lookup/open-paths logic need updating in two places. Could a rename-aware variant of the helpers be used instead to keep one code path?

File: src/platform/workflow/core/services/workflowService.test.ts [hunk 6]
```diff
@@ -307,6 +307,56 @@ describe('useWorkflowService', () => {
     })
   })
 
+  describe('afterLoadNewGraph', () => {
```
Comment (christian-byrne) [inline src/platform/workflow/core/services/workflowService.test.ts:388]: suggestion (non-blocking): The `saveWorkflow` and `saveWorkflowAs` tests were deleted, but the underlying store implementations were changed (save-then-swap ordering, inline lookup mutation for rename). It would be good to have replacement tests covering the new ordering, even if the old test shapes no longer apply.

File: src/platform/workflow/core/services/workflowService.test.ts [hunk 7]
```diff
@@ -307,6 +307,56 @@ describe('useWorkflowService', () => {
...
+      } as never)
+
+      expect(workflowStore.getWorkflowByPath).toHaveBeenCalledWith(
+        'workflows/repeat.json'
+      )
+      expect(workflowStore.openWorkflow).toHaveBeenCalledWith(existingWorkflow)
+      expect(existingWorkflow.changeTracker.reset).toHaveBeenCalled()
+      expect(existingWorkflow.changeTracker.restore).toHaveBeenCalled()
+      expect(workflowStore.createNewTemporary).not.toHaveBeenCalled()
+    })
```
Comment (christian-byrne) [inline src/platform/workflow/core/services/workflowService.test.ts:435]: nitpick (non-blocking): The new `afterLoadNewGraph` tests cover same-ID and both-undefined-ID cases but not the mixed case (one side has an ID, the other doesn't). A test for that scenario would exercise the gap noted in the idempotency gate above.

**Review by christian-byrne — COMMENTED** [review]
nitpick (non-blocking): `workflowStore.ts` line 33 -- `export { ComfyWorkflow, type LoadedComfyWorkflow }` uses inline `type` in the export. For consistency with the import convention of separating type imports, consider splitting to `export { ComfyWorkflow }` + `export type { LoadedComfyWorkflow }`.

File: src/platform/workflow/management/stores/workflowStore.ts (hunk 5 above)
Comment (DrJKL) [reply src/platform/workflow/management/stores/workflowStore.ts:490]: @coderabbitai Open an issue to follow up on this.
