### PR TITLE
fix Vue node widgets should be in disabled state if their slots are connected with a link

### LINKED ISSUE #5692: The widget value is still editable or not hidden when converted to input.
https://github.com/user-attachments/assets/95468d24-8f74-4ac1-b557-4a6c84867add

Image

1. Can we also add an input dot style after the widget is automatically converted to an input? 
2. The widget value is still editable

### PR DESCRIPTION
**Pull request by christian-byrne**
## Summary

Fixes https://github.com/Comfy-Org/ComfyUI_frontend/issues/5692 by making widget link connection status trigger on change so Vue widgets with connected links could properly switch to the `disabled` state when they are implicitly converted to inputs. 

## Changes

- **What**: Added `node:slot-links:changed` event tracking and reactive slot data synchronization for Vue widgets

```mermaid
graph TD
    A[Widget Link Change] --> B[NodeInputSlot.link setter]
    B --> C{Is Widget Input?}
    C -->|Yes| D[Trigger slot-links:changed]
    C -->|No| E[End]
    D --> F[Graph Event Handler]
    F --> G[syncNodeSlotData]
    G --> H[Update Vue Reactive Data]
    H --> I[Widget Re-render]
    
    style A fill:#f9f9f9,stroke:#333,color:#000
    style I fill:#f9f9f9,stroke:#333,color:#000
```

## Review Focus

Widget reactivity performance with frequent link changes and event handler memory management in graph operations.

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-5834-fix-Vue-node-widgets-should-be-in-disabled-state-if-their-slots-are-connected-with-a-link-27c6d73d365081f6a6c3c1ddc3905c5e) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/renderer/extensions/vueNodes/components/LGraphNode.vue [hunk 1]
```diff
@@ -113,7 +113,7 @@
         <!-- Widgets rendered at reduced+ detail -->
         <NodeWidgets
           v-if="nodeData.widgets?.length"
-          v-memo="[nodeData.widgets?.length]"
+          v-memo="[nodeData.widgets?.length, nodeData.inputs]"
```
Comment (DrJKL) [inline src/renderer/extensions/vueNodes/components/LGraphNode.vue]: What would happen if we just removed the [`v-memo`](https://vuejs.org/api/built-in-directives.html#v-memo) and let Vue handle it?
```suggestion
```

File: src/lib/litegraph/src/node/NodeInputSlot.ts [hunk 2]
```diff
@@ -12,10 +12,11 @@ import { type IDrawOptions, NodeSlot } from '@/lib/litegraph/src/node/NodeSlot'
 import type { SubgraphInput } from '@/lib/litegraph/src/subgraph/SubgraphInput'
 import type { SubgraphOutput } from '@/lib/litegraph/src/subgraph/SubgraphOutput'
 import { isSubgraphInput } from '@/lib/litegraph/src/subgraph/subgraphUtils'
+import { NodeSlotType } from '@/lib/litegraph/src/types/globalEnums'
 import type { IBaseWidget } from '@/lib/litegraph/src/types/widgets'
 
 export class NodeInputSlot extends NodeSlot implements INodeInputSlot {
-  link: LinkId | null
+  private _link: LinkId | null
```
Comment (DrJKL) [inline src/lib/litegraph/src/node/NodeInputSlot.ts]: Two points of personal preference for this pattern:
I usually like an `Internal` suffix, i.e. `linkInternal` to the underscore prefix. Feels more expressive and helps with IDEs' outlines if you sort fields lexicographically.
I also don't love `null` over `undefined` since it does usually entail adding nullish coalescing to pick the specific correct absent value (when otherwise the absent value is `undefined` in the default case)

File: src/lib/litegraph/src/node/NodeInputSlot.ts [hunk 3]
```diff
@@ -41,11 +42,37 @@ export class NodeInputSlot extends NodeSlot implements INodeInputSlot {
...
+    const index = this.node.inputs.indexOf(this)
+    if (index === -1) return
+
+    graph.trigger('node:slot-links:changed', {
+      nodeId: this.node.id,
+      slotType: NodeSlotType.INPUT,
+      slotIndex: index,
+      connected: this._link != null,
+      linkId: this._link ?? null
+    })
```
Comment (DrJKL) [inline src/lib/litegraph/src/node/NodeInputSlot.ts]: This feels like something that we should be doing in a store, if not now, then soon. I don't like complex decisions being made in components.

File: src/lib/litegraph/src/node/NodeInputSlot.ts [hunk 4]
```diff
@@ -41,11 +42,37 @@ export class NodeInputSlot extends NodeSlot implements INodeInputSlot {
...
+    if (!graph) return
+
+    const index = this.node.inputs.indexOf(this)
+    if (index === -1) return
+
+    graph.trigger('node:slot-links:changed', {
+      nodeId: this.node.id,
+      slotType: NodeSlotType.INPUT,
+      slotIndex: index,
+      connected: this._link != null,
```
Comment (DrJKL) [inline src/lib/litegraph/src/node/NodeInputSlot.ts]:
```suggestion
      connected: this.isConnected,
```

File: src/lib/litegraph/src/node/NodeInputSlot.ts [hunk 5]
```diff
@@ -41,11 +42,37 @@ export class NodeInputSlot extends NodeSlot implements INodeInputSlot {
...
+      linkId: this._link ?? null
```
Comment (DrJKL) [inline src/lib/litegraph/src/node/NodeInputSlot.ts]:
```suggestion
      linkId: this.link
```

File: src/lib/litegraph/src/node/NodeInputSlot.ts [hunk 6]
```diff
@@ -41,11 +42,37 @@ export class NodeInputSlot extends NodeSlot implements INodeInputSlot {
...
+    const graph = this.node.graph
+    if (!graph) return
+
+    const index = this.node.inputs.indexOf(this)
+    if (index === -1) return
+
+    graph.trigger('node:slot-links:changed', {
+      nodeId: this.node.id,
+      slotType: NodeSlotType.INPUT,
+      slotIndex: index,
```
Comment (DrJKL) [inline src/lib/litegraph/src/node/NodeInputSlot.ts]: option:
```suggestion
    const slotIndex = this.node.inputs.indexOf(this)
    if (slotIndex === -1) return

    graph.trigger('node:slot-links:changed', {
      nodeId: this.node.id,
      slotType: NodeSlotType.INPUT,
      slotIndex,
```

File: src/composables/graph/useGraphNodeManager.ts [hunk 7]
```diff
@@ -66,6 +66,17 @@ export function useGraphNodeManager(graph: LGraph): GraphNodeManager {
   // Non-reactive storage for original LiteGraph nodes
   const nodeRefs = new Map<string, LGraphNode>()
 
+  const syncNodeSlotData = (nodeId: string, node: LGraphNode) => {
+    const currentData = vueNodeData.get(nodeId)
+    if (!currentData) return
+
+    vueNodeData.set(nodeId, {
+      ...currentData,
+      inputs: node.inputs ? [...node.inputs] : undefined,
```
Comment (DrJKL) [inline src/composables/graph/useGraphNodeManager.ts]: Not for this PR, but what if we defined inputs and outputs as being required, so that a lack of them would just be an empty array? Would that simplify some of the logic?

**Review by DrJKL — DISMISSED** [review]

**Review by webfiltered — COMMENTED** [review]
I feel like this might be around 40K lines-too-many.  Give or take.  😁

File: src/composables/graph/useGraphNodeManager.ts [hunk 8]
```diff
@@ -66,6 +78,22 @@ export function useGraphNodeManager(graph: LGraph): GraphNodeManager {
...
+    if (!nodeRef || !currentData) return
+
+    const refreshedData = extractVueNodeData(nodeRef)
+
+    vueNodeData.set(nodeId, {
+      ...currentData,
+      widgets: refreshedData.widgets,
+      inputs: refreshedData.inputs,
+      outputs: refreshedData.outputs
+    })
```
Comment (webfiltered) [inline src/composables/graph/useGraphNodeManager.ts]:
```suggestion
    const { widgets, inputs, outputs } = extractVueNodeData(nodeRef)

    vueNodeData.set(nodeId, { ...currentData, widgets, inputs, outputs })
```

This is a sidegrade at best, but... I wanted to see if it would fit.  After I checked, the "work" was already done, so please take / discard as you like.

File: src/composables/graph/useGraphNodeManager.ts [hunk 9]
```diff
@@ -444,63 +474,59 @@ export function useGraphNodeManager(graph: LGraph): GraphNodeManager {
...
+          refreshNodeSlots(String(slotLinksEvent.nodeId))
         }
       }
+    }
 
-      // Call original trigger handler if it exists
-      if (originalOnTrigger) {
-        originalOnTrigger(action, param)
+    const isTriggerAction = (value: string): value is LGraphTriggerAction =>
+      Object.prototype.hasOwnProperty.call(triggerHandlers, value)
```
Comment (webfiltered) [inline src/composables/graph/useGraphNodeManager.ts]:
```suggestion
      Object.hasOwn(triggerHandlers, value)
```

File: src/renderer/extensions/vueNodes/components/NodeWidgets.vue [hunk 10]
```diff
@@ -129,12 +130,21 @@ const processedWidgets = computed((): ProcessedWidget[] => {
 
     const vueComponent = getComponent(widget.type) || WidgetInputText
 
+    const slotMetadata = widget.slotMetadata
```
Comment (webfiltered) [inline src/renderer/extensions/vueNodes/components/NodeWidgets.vue:133]:
```suggestion
    const { slotMetadata } = widget
```

nit

**Review by webfiltered — COMMENTED** [review]
Most importantly: LGTM!

I'm still a little confused about why we're using the `LGraph` "trigger" system - the reason I mention that is just because it feels like we have added a few iterations of  complexity and workarounds.

If we need to revisit again, maybe we should go more nuclear on the fix, and remove any possibility of decade-old design decisions haunting us any further?

File: src/renderer/extensions/vueNodes/components/NodeWidgets.vue (hunk 10 above)
Comment (DrJKL) [reply src/renderer/extensions/vueNodes/components/NodeWidgets.vue:133]: Could pull off options at the same time

File: src/lib/litegraph/src/LGraphNode.ts [hunk 11]
```diff
@@ -3009,6 +3019,15 @@ export class LGraphNode
...
         // remove there
         input.link = null
+        if (input.widget) {
+          graph.trigger('node:slot-links:changed', {
+            nodeId: target.id,
+            slotType: NodeSlotType.INPUT,
+            slotIndex: link_info.target_slot,
+            connected: false,
+            linkId: link_info.id
+          })
```
Comment (DrJKL) [inline src/lib/litegraph/src/LGraphNode.ts:3029]: If this is the same in all three locations, how would you feel about extracting something like `maybeTriggerLinkChange(...)`?

**Comment by christian-byrne** [comment]
> I'm still a little confused about why we're using the LGraph "trigger" system - the reason I mention that is just because it feels like we have added a few iterations of complexity and workarounds.
> 
> If we need to revisit again, maybe we should go more nuclear on the fix, and remove any possibility of decade-old design decisions haunting us any further?

I think everyone who reads this all wants to go nuclear on the fix, but it doesn't fully align with business goals to dedicate a lot of time to doing it. We will gradually replace the system with signals-based implementation.

**Comment by christian-byrne** [comment]
Planning on making changes:

- Properly type events to not require any extra unneccesary assertions or awkward reflection, using standard patterns
- Add e2e tests for the disabled state on linked widgets

File: src/lib/litegraph/src/LGraph.ts [hunk 12]
```diff
@@ -1180,8 +1191,33 @@ export class LGraph
...
+  trigger(action: string, param: unknown): void
   trigger(action: string, param: unknown) {
-    this.onTrigger?.(action, param)
+    // Convert to discriminated union format for typed handlers
+    if (
+      action === 'node:slot-links:changed' &&
+      param &&
+      typeof param === 'object'
+    ) {
+      this.onTrigger?.({ type: action, ...param } as LGraphTriggerEvent)
```
[the remark this answers is not in the document]
Comment (christian-byrne) [reply src/lib/litegraph/src/LGraph.ts]: That's pretty paranoid

File: src/lib/litegraph/src/LGraphNode.ts (hunk 11 above)
Comment (christian-byrne) [reply src/lib/litegraph/src/LGraphNode.ts:3029]: I think it would only be simplified if it were to be made a class instance property of some sort, which would start to go backwards a bit. If it's moved to a more pure helper, then it becomes even more code, I think. Don't see a way to simplify/refactor cleanly.

File: src/composables/graph/useGraphNodeManager.ts [hunk 13]
```diff
@@ -66,6 +79,22 @@ export function useGraphNodeManager(graph: LGraph): GraphNodeManager {
   // Non-reactive storage for original LiteGraph nodes
   const nodeRefs = new Map<string, LGraphNode>()
 
+  const refreshNodeSlots = (nodeId: string) => {
+    const nodeRef = nodeRefs.get(nodeId)
+    const currentData = vueNodeData.get(nodeId)
+
+    if (!nodeRef || !currentData) return
+
+    const refreshedData = extractVueNodeData(nodeRef)
```
[the remark this answers is not in the document]
Comment (christian-byrne) [reply src/composables/graph/useGraphNodeManager.ts]: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5834/commits/07de517caff3019ea1418f6085c9ab78ff9b614d

File: src/lib/litegraph/src/LGraphNode.ts [hunk 14]
```diff
@@ -2852,7 +2852,17 @@ export class LGraphNode
     output.links ??= []
     output.links.push(link.id)
     // connect in input
-    inputNode.inputs[inputIndex].link = link.id
+    const targetInput = inputNode.inputs[inputIndex]
+    targetInput.link = link.id
+    if (targetInput.widget) {
+      graph.trigger('node:slot-links:changed', {
```
[the remark this answers is not in the document]
Comment (christian-byrne) [reply src/lib/litegraph/src/LGraphNode.ts:2858]: See other comment regarding refactoring this.

File: src/lib/litegraph/src/types/graphTriggers.ts [hunk 15]
```diff
@@ -0,0 +1,37 @@
...
+}
+
+interface NodeSlotErrorsChangedEvent {
+  type: 'node:slot-errors:changed'
+  nodeId: string | number
+}
+
+interface NodeSlotLinksChangedEvent {
+  type: 'node:slot-links:changed'
+  nodeId: string | number
```
[the remark this answers is not in the document]
Comment (christian-byrne) [reply src/lib/litegraph/src/types/graphTriggers.ts]: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5834/commits/ddbc895eff4b34f944d1e5562b166b8771e04ac6

File: src/composables/graph/useGraphNodeManager.ts [hunk 16]
```diff
@@ -444,63 +475,64 @@ export function useGraphNodeManager(graph: LGraph): GraphNodeManager {
...
-              : undefined,
-            outputs: litegraphNode.outputs
-              ? [...litegraphNode.outputs]
-              : undefined
-          })
+      },
+      'node:slot-errors:changed': (slotErrorsEvent) => {
+        refreshNodeSlots(String(slotErrorsEvent.nodeId))
+      },
+      'node:slot-links:changed': (slotLinksEvent) => {
```
[the remark this answers is not in the document]
Comment (christian-byrne) [reply src/composables/graph/useGraphNodeManager.ts:529]: No, some things should not be debounced.

File: src/renderer/extensions/vueNodes/components/NodeWidgets.vue [hunk 17]
```diff
@@ -129,12 +130,21 @@ const processedWidgets = computed((): ProcessedWidget[] => {
...
+
+    let widgetOptions = widget.options
+    if (slotMetadata?.linked) {
```
[the remark this answers is not in the document]
Comment (christian-byrne) [reply src/renderer/extensions/vueNodes/components/NodeWidgets.vue:139]: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5834/commits/eff84313dd841127218ae75d80ff18c860729e06

File: src/lib/litegraph/src/LGraph.ts [hunk 18]
```diff
@@ -1180,8 +1191,33 @@ export class LGraph
   }
 
   // ********** GLOBALS *****************
+  trigger<A extends LGraphTriggerAction>(
+    action: A,
+    param: LGraphTriggerParam<A>
+  ): void
+  trigger(action: string, param: unknown): void
   trigger(action: string, param: unknown) {
```
[the remark this answers is not in the document]
Comment (christian-byrne) [reply src/lib/litegraph/src/LGraph.ts:1199]: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5834/commits/3e542a0d0b4cfca359b6e5868dc4fb124f55f2dd
