### PR TITLE
forward mouse events from textareas to canvas

### LINKED ISSUE #1773: [Bug]: Canvas pan using middle-click does not work on DOM widgets
### Frontend Version

*

### Expected Behavior

Middle click and drag pans the canvas (unless intentionally blocked by overlay / modal).

### Actual Behavior

DOM elements intercept the middle click, and it never reaches the canvas.  Middle click and drag does nothing.

### Steps to Reproduce

Middle click DOM element and drag

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

### What browsers do you use to access the UI ?

Google Chrome

### Other

_No response_

┆Issue is synchronized with this [Notion page](https://www.notion.so/Bug-Canvas-pan-using-middle-click-does-not-work-on-DOM-widgets-15b6d73d365081ff855bd13051739e72) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by fahdarafat**
This should fix [1773](https://github.com/Comfy-Org/ComfyUI_frontend/issues/1773).
I'm not sure though if there are more DOM elements to handle. This currently only handles textareas

https://github.com/user-attachments/assets/3811eddd-9d01-4c8c-a918-a801e6d0db01

┆Issue is synchronized with this [Notion page](https://www.notion.so/1911-forward-mouse-events-from-textareas-to-canvas-15c6d73d3650810f8c4cdc68d026c862) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by huchenlei** [comment]
@webfiltered Can you take a look at this PR? Do we want a playwright test to verify this is working?

File: src/scripts/widgets.ts [hunk 1]
```diff
@@ -341,6 +341,26 @@ function addMultilineWidget(node, name: string, opts, app: ComfyApp) {
     widget.callback?.(widget.value)
   })
 
+  inputEl.addEventListener('mousedown', (event: PointerEvent) => {
```
Comment (webfiltered) [inline src/scripts/widgets.ts]:
```suggestion
  inputEl.addEventListener('pointerdown', (event: PointerEvent) => {
```

Need to use `pointer` events for this - `mouse` lacks some required features.

File: src/scripts/widgets.ts [hunk 2]
```diff
@@ -341,6 +341,26 @@ function addMultilineWidget(node, name: string, opts, app: ComfyApp) {
...
+    if (event.button === 1) {
+      event.preventDefault()
+      app.canvas.processMouseDown(event)
+    }
+  })
+
+  inputEl.addEventListener('mousemove', (event: PointerEvent) => {
```
Comment (webfiltered) [inline src/scripts/widgets.ts]:
```suggestion
  inputEl.addEventListener('pointermove', (event: PointerEvent) => {
```

File: src/scripts/widgets.ts [hunk 3]
```diff
@@ -341,6 +341,26 @@ function addMultilineWidget(node, name: string, opts, app: ComfyApp) {
...
+    if (event.buttons === 4) {
+      app.canvas.pointer.onDragStart(app.canvas.pointer)
+      app.canvas.processMouseMove(event)
+    }
+  })
+
+  inputEl.addEventListener('mouseup', (event: PointerEvent) => {
```
Comment (webfiltered) [inline src/scripts/widgets.ts]:
```suggestion
  inputEl.addEventListener('pointerup', (event: PointerEvent) => {
```

File: src/scripts/widgets.ts [hunk 4]
```diff
@@ -341,6 +341,26 @@ function addMultilineWidget(node, name: string, opts, app: ComfyApp) {
     widget.callback?.(widget.value)
   })
 
+  inputEl.addEventListener('mousedown', (event: PointerEvent) => {
+    if (event.button === 1) {
+      event.preventDefault()
```
Comment (webfiltered) [inline src/scripts/widgets.ts]:
```suggestion
```

It's alright to let this hit both the DOM element and canvas in this instance.  Otherwise there's no way for anyone to get a middle click on their dom widget.

File: src/scripts/widgets.ts [hunk 5]
```diff
@@ -341,6 +341,26 @@ function addMultilineWidget(node, name: string, opts, app: ComfyApp) {
...
+      app.canvas.processMouseDown(event)
+    }
+  })
+
+  inputEl.addEventListener('mousemove', (event: PointerEvent) => {
+    if (event.buttons === 4) {
+      app.canvas.pointer.onDragStart(app.canvas.pointer)
```
Comment (webfiltered) [inline src/scripts/widgets.ts]:
```suggestion
```

Now that we're using `pointer` instead of `mouse`, we can remove the workaround - creative, though!

File: src/scripts/widgets.ts [hunk 6]
```diff
@@ -341,6 +341,26 @@ function addMultilineWidget(node, name: string, opts, app: ComfyApp) {
...
 
+  inputEl.addEventListener('mousedown', (event: PointerEvent) => {
+    if (event.button === 1) {
+      event.preventDefault()
+      app.canvas.processMouseDown(event)
+    }
+  })
+
+  inputEl.addEventListener('mousemove', (event: PointerEvent) => {
+    if (event.buttons === 4) {
```
Comment (webfiltered) [inline src/scripts/widgets.ts]:
```suggestion
    if ((event.buttons & 4) === 4) {
```

`buttons` is a binary flag value (or "register" if you're familiar with hardware stuff) - this way it will match even if you are holding middle button and another button.

**Review by webfiltered — CHANGES_REQUESTED** [review]
Awesome, thank you!  I had this on my to-do list, so it's much appreciated!

(this review looks like a lot of changes, but really it's just three very minor ones)

**Review by webfiltered — APPROVED** [review]

**Review by huchenlei — APPROVED** [review]
