### PR TITLE
fix: node hover previews overlapping with sidebar

### LINKED ISSUE #6130: Margin missing from sidebar node previews
Node hover previews in the side menu require margin in order to read descriptions properly

Image

### ComfyUI Frontend Version

1.30.1

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-6130-Margin-missing-from-sidebar-node-previews-2906d73d365081b28be9dc37181a02e2) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by christian-byrne**
Fixes https://github.com/Comfy-Org/ComfyUI_frontend/issues/6130 -- node previews are not positioned in correct location after https://github.com/Comfy-Org/ComfyUI_frontend/pull/5980

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-6232-fix-node-hover-previews-overlapping-with-sidebar-2956d73d365081b2a470f7fb399fda99) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/components/sidebar/tabs/nodeLibrary/NodeTreeLeaf.vue [hunk 1]
```diff
@@ -132,31 +132,28 @@ function deleteBlueprint() {
...
 
-const previewRef = ref<InstanceType<typeof NodePreview> | null>(null)
 const nodePreviewStyle = ref<CSSProperties>({
-  position: 'absolute',
+  position: 'fixed',
   top: '0px',
-  left: '0px'
+  left: '0px',
+  pointerEvents: 'none',
+  zIndex: 1001
```
Comment (christian-byrne) [inline src/components/sidebar/tabs/nodeLibrary/NodeTreeLeaf.vue:140]: Not really part of the bugfix, but I noticed in testing different window sizes that the preview was getting placed below the minimap so I added this to fix that as well.

File: src/components/sidebar/tabs/nodeLibrary/NodeTreeLeaf.vue [hunk 2]
```diff
@@ -132,31 +132,28 @@ function deleteBlueprint() {
...
-  } else {
-    nodePreviewStyle.value.left = `${targetRect.left - 400}px`
-  }
+  const margin = 40
+
+  nodePreviewStyle.value.top = `${targetRect.top}px`
+  nodePreviewStyle.value.left =
+    sidebarLocation.value === 'left'
+      ? `${targetRect.right + margin}px`
+      : `${targetRect.left - margin}px`
```
Comment (DrJKL) [inline src/components/sidebar/tabs/nodeLibrary/NodeTreeLeaf.vue:154]: I would expect the style to set `right` to the `left` for the flipped sidebar, not `left` to `left`

Comment (DrJKL) [reply src/components/sidebar/tabs/nodeLibrary/NodeTreeLeaf.vue:154]: Instead of setting and then transforming

**Review by DrJKL — APPROVED** [review]
