### PR TITLE
fix: add fixed min-width to sidebar panels to prevent content clipping

### LINKED ISSUE #7210: [Assets panel] The download button will not be fully displayed under certain panel widths.
Image

https://github.com/user-attachments/assets/5c98fd1d-49d5-4cd8-acf5-731ac5618d28

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-7210-Assets-panel-The-download-button-will-not-be-fully-displayed-under-certain-panel-wid-2c16d73d365081b78424e5818b0f5a11) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jtydhr88**
## Summary

The default 10% min-size is too small for panels like Media Assets, causing content to be clipped. 
Use a fixed minimum width to ensure the panel content displays properly.

fix https://github.com/Comfy-Org/ComfyUI_frontend/issues/7210

## Screenshots

https://github.com/user-attachments/assets/65a15f0f-45c1-4361-adc9-eee4ccfad0ee

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-7212-fix-add-fixed-min-width-to-sidebar-panels-to-prevent-content-clipping-2c16d73d365081d8a5a4de30c8eb5e07) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/components/LiteGraphCanvasSplitterOverlay.vue [hunk 1]
```diff
@@ -31,7 +31,10 @@
             display:
               sidebarPanelVisible && sidebarLocation === 'left'
                 ? 'flex'
-                : 'none'
+                : 'none',
+            minWidth: sidebarPanelVisible
+              ? `${SIDEBAR_MIN_WIDTH_PX}px`
+              : undefined
```
Comment (DrJKL) [inline src/components/LiteGraphCanvasSplitterOverlay.vue]: Could you do this in the `class`?
I think it'd be:
```html
:class="cn('side-bar-panel bg-comfy-menu-bg pointer-events-auto', sidebarPanelVisible && 'min-w-78')
```

**Review by DrJKL — CHANGES_REQUESTED** [review]
If you wanted to use tailwind utilities for the display property too I would not be mad about it 😉

File: src/components/LiteGraphCanvasSplitterOverlay.vue [hunk 2]
```diff
@@ -24,7 +24,12 @@
       >
         <SplitterPanel
           v-if="sidebarLocation === 'left' && !focusMode"
-          class="side-bar-panel bg-comfy-menu-bg pointer-events-auto"
+          :class="
+            cn(
+              'side-bar-panel bg-comfy-menu-bg pointer-events-auto',
+              sidebarPanelVisible && 'min-w-78'
+            )
+          "
```
[the remark this answers is not in the document]
Comment (jtydhr88) [reply src/components/LiteGraphCanvasSplitterOverlay.vue:32]: not a make-sence suggestion, this PR should only focus on the currect issue, should not include another thing

File: src/components/LiteGraphCanvasSplitterOverlay.vue (hunk 1 above)
Comment (jtydhr88) [reply src/components/LiteGraphCanvasSplitterOverlay.vue]: fixed

**Review by DrJKL — APPROVED** [review]
