### PR TITLE
fix: prevent canvas zoom when scrolling image history dropdown

### LINKED ISSUE #10549: fix: the scroll up and down of the dropbox of the the upload image dropdown widget
### What problem are you experiencing?

Fix scroll behavior: The image history dropdown has a fixed height, but scrolling currently triggers canvas zooming. We need to add a check so that when the mouse is over the dropdown, the wheel scrolls the list instead of zooming the map.

### When does this problem occur?

The wheel scrolls the the map zooming rathar than the list up-and-down.

### How often do you encounter this problem?

Multiple times per day

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-10549-fix-the-scroll-up-and-down-of-the-dropbox-of-the-the-upload-image-dropdown-widget-32f6d73d365081c9a3c3caa1fa2d941b) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by kaili-yang**
## Summary
 
Fix #10549 where using the mouse wheel over the image history dropdown (e.g., in "Load Image" nodes) would trigger canvas zooming instead of scrolling the list.

## Changes
Added `data-capture-wheel="true" ` to the root container. This attribute is used by the `TransformPane` to identify elements that should consume wheel events.

## Screenshots
 
after

https://github.com/user-attachments/assets/8935a1ca-9053-4ef1-9ab8-237f43eabb35

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-10550-fix-prevent-canvas-zoom-when-scrolling-image-history-dropdown-32f6d73d365081c4ad09f763481ef8c2) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuActions.vue [hunk 1]
```diff
@@ -103,6 +103,7 @@ function toggleBaseModelSelection(item: FilterOption) {
   <div class="text-secondary flex gap-2 px-4">
     <FormSearchInput
       v-model="searchQuery"
+      :autofocus="true"
```
Comment (jtydhr88) [inline src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuActions.vue]: Nit: :autofocus="true" → autofocus would be more consistent with the rest of the codebase (see WorkflowTemplateSelectorDialog.vue, CustomizationDialog.vue, etc.)

**Review by jtydhr88 — CHANGES_REQUESTED** [review]

File: src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuActions.vue (hunk 1 above)
Comment (kaili-yang) [reply src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuActions.vue]: It's a good point. Fixed.

**Review by jtydhr88 — APPROVED** [review]
LGTM, and I think the falure test does not caused by this changes

**Comment by jtydhr88** [comment]
the recording has another issue that load image panel on wrong location, but it should be fix in followup PR

File: src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenu.test.ts [hunk 2]
```diff
@@ -110,4 +110,19 @@ describe('FormDropdownMenu', () => {
...
+        stubs: {
+          FormDropdownMenuFilter: true,
+          FormDropdownMenuActions: true,
+          VirtualGrid: true
+        }
+      }
+    })
+
+    expect(wrapper.attributes('data-capture-wheel')).toBe('true')
+  })
```
Comment (DrJKL) [inline src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenu.test.ts:127]: This is kind of a change-detector. Ideally we'd test this via Playwright using actual scroll events.
@coderabbitai Open an issue to add scroll handling specs.

**Review by DrJKL — APPROVED** [review]

**Review by DrJKL — APPROVED** [review]
