### PR TITLE
fix: node shape not reactive in vueNodes mode

### LINKED ISSUE #7144: ComfyUI 2.0
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [x] I have searched existing issues to make sure this isn't a duplicate
- [x] I have tested with all custom nodes disabled ([see how](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled))

### What happened?

The current available options for the Node shape are only Default, Round and Box.  Card was left out.  Also, no matter which option you choose, the shape of the nodes doesn't change.  They are locked to the rounded appearance.

### Steps to Reproduce

1.  Right click node and select shapes menu
2.  Click on any of the three available options
3.

### How is this affecting you?

Crashes ComfyUI completely

### ComfyUI Frontend Version

1.32.10

### Browser

Chrome/Chromium

### Console Errors

```javascript

```

### Logs

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jtydhr88**
## Summary

add node shape support in vueNodes

fix https://github.com/Comfy-Org/ComfyUI_frontend/issues/7144

## Screenshots (if applicable)

https://github.com/user-attachments/assets/df8a4fa6-5686-435d-a814-4fe3990f7e69

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-7302-fix-node-shape-not-reactive-in-vueNodes-mode-2c56d73d3650811c9ef5e4fe49c94f55) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/renderer/extensions/vueNodes/components/LGraphNode.vue [hunk 1]
```diff
@@ -21,10 +22,11 @@
...
         cursorClass,
         {
-          'before:rounded-2xl before:pointer-events-none before:absolute before:bg-bypass/60 before:inset-0':
+          [beforeShapeClass +
+          ' before:pointer-events-none before:absolute before:bg-bypass/60 before:inset-0']:
             bypassed,
-          'before:rounded-2xl before:pointer-events-none before:absolute before:inset-0':
-            muted,
+          [beforeShapeClass +
+          ' before:pointer-events-none before:absolute before:inset-0']: muted,
```
Comment (DrJKL) [inline src/renderer/extensions/vueNodes/components/LGraphNode.vue]:
```suggestion
          `${beforeShapeClass} before:pointer-events-none before:absolute before:inset-0`: muted,
```

File: src/renderer/extensions/vueNodes/components/LGraphNode.vue [hunk 2]
```diff
@@ -21,10 +22,11 @@
         outlineClass,
         cursorClass,
         {
-          'before:rounded-2xl before:pointer-events-none before:absolute before:bg-bypass/60 before:inset-0':
+          [beforeShapeClass +
+          ' before:pointer-events-none before:absolute before:bg-bypass/60 before:inset-0']:
```
Comment (DrJKL) [inline src/renderer/extensions/vueNodes/components/LGraphNode.vue]:
```suggestion
          `${beforeShapeClass} before:pointer-events-none before:absolute before:bg-bypass/60 before:inset-0`:
```

**Review by DrJKL — DISMISSED** [review]

**Review by DrJKL — APPROVED** [review]

**Review by christian-byrne — APPROVED** [review]
