### PR TITLE
fix: prevent white flash when opening mask editor

### LINKED ISSUE #9852: Fix: Flash of white screen when opening Full Editor Mask
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [ ] I have custom nodes enabled

### What happened?

In cloud environments, triggering the **mask editor** results in a 1-2s white flash (blank frame) each time before the UI renders.

### Steps to Reproduce

Create a "Load Image" node, upload an image, then click the `Edit or mask image` icon.

https://github.com/user-attachments/assets/42281762-a6b2-4506-86d2-be10715f3f53

### How is this affecting you?

Visual/UI issue only

### ComfyUI Frontend Version

1.3.45

### Browser

Chrome/Chromium

### PR DESCRIPTION
**Pull request by dante01yoon**
## Summary

- Remove hardcoded `bg-white` from mask editor canvas background div to prevent white flash on dialog open
- Add a loading spinner while the mask editor initializes (image loading, canvas setup, GPU resources)
- Background color is set dynamically by `setCanvasBackground()` after initialization

Fixes #9852

### AS IS

https://github.com/user-attachments/assets/7da61e32-671b-4056-b5ec-8cb246fc7689

### TO BE 
https://github.com/user-attachments/assets/bfdedc69-f690-42c5-8591-619623c04f55

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-9860-fix-prevent-white-flash-when-opening-mask-editor-3226d73d365081de9b7ad4622438e6ed) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/components/maskeditor/MaskEditorContent.vue [hunk 1]
```diff
@@ -35,7 +35,14 @@
           'z-40': store.activeLayer === 'mask'
         }"
       />
-      <div ref="canvasBackgroundRef" class="size-full bg-white" />
+      <div ref="canvasBackgroundRef" class="size-full" />
+    </div>
+
+    <div
```
Comment (christian-byrne) [inline src/components/maskeditor/MaskEditorContent.vue]: suggestion: Consider reusing the existing `LoadingOverlay` component instead of the custom spinner.

The custom CSS spinner (lines 239-252) duplicates what `LoadingOverlay.vue` already provides -- same `absolute inset-0 z-50 flex items-center justify-center` layout, plus theme-aware colors (`border-muted-foreground`/`border-t-base-foreground` vs hardcoded white), Tailwind's `animate-spin`, a semi-transparent backdrop, and a fade transition.

The hardcoded `rgb(255 255 255 / 20%)` / `rgb(255 255 255 / 80%)` would also be invisible on light themes.

```vue
<LoadingOverlay :loading="!initialized" size="sm" />
```
```ts
import LoadingOverlay from '@/components/common/LoadingOverlay.vue'
```
Then the custom `.mask-editor-spinner` CSS and `@keyframes spin` block can be removed.

Comment (dante01yoon) [reply src/components/maskeditor/MaskEditorContent.vue]: Applied. using LoadingOverlay instead of custom element

**Review by christian-byrne — APPROVED** [review]
LGTM
