### PR TITLE
Fix clipboard

### LINKED ISSUE #98: [Bug] Double paste when pasting in textarea
Reproduction steps:
- Copy a node
- Copy some text
- Focus on CLIP node's text area
- Keyboard `Ctrl + V`
- Observe that the text is pasted and a node is also pasted

This behaviour does not happen in main ComfyUI repo's impl

### PR DESCRIPTION
**Pull request by huchenlei**
Closes https://github.com/Comfy-Org/ComfyUI_frontend/issues/98

### CODE REVIEW

File: src/scripts/app.ts [hunk 1]
```diff
@@ -1133,16 +1134,17 @@ export class ComfyApp {
...
+        (e.target instanceof HTMLInputElement && e.target.type === "text")
       ) {
         // Default system copy
         return;
       }
 
       // copy nodes and clear clipboard
       if (
-        e.target instanceof HTMLElement &&
+        e.target instanceof Element &&
```
Comment (huchenlei) [inline src/scripts/app.ts:1147]: Loose the typecheck constraint to `Element`.
