### PR TITLE
fix: exclude muted/bypassed nodes from missing asset detection

### LINKED ISSUE #13256: Missing model error for disconnected and bypassed loader nodes
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Expected Behavior

Until end of March of 2036 all not connected, disabled or bypassed model loaders with missing models were not considered as errors. 

### Actual Behavior

All not connected, disabled or bypassed model loaders with missing models now considered as errors.

Image

### Steps to Reproduce

Add model loader node and select some checkpoint or lora. Bypass that node and keep it not connected. Rename selected model and restart comfyui.

### Debug Logs

```powershell
Found comfy_kitchen backend triton: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_mxfp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Found comfy_kitchen backend cuda: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_mxfp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_mxfp8', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_mxfp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_mxfp8', 'scaled_mm_nvfp4']}
Checkpoint files will always be loaded safely.
Total VRAM 16379 MB, total RAM 130974 MB
pytorch version: 2.10.0+cu130
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using async weight offloading with 2 streams
Enabled pinned memory 52389.0
working around nvidia conv3d memory bug.
Using pytorch attention
aimdo: src-win/cuda-detour.c:77:INFO:aimdo_setup_hooks: found driver at 00007FF897BA0000, installing 4 hooks
aimdo: src-win/cuda-detour.c:61:DEBUG:install_hook_entrys: hooks successfully installed
aimdo: src/control.c:69:INFO:comfy-aimdo inited for GPU: NVIDIA GeForce RTX 4060 Ti (VRAM: 16379 MB)
DynamicVRAM support detected and enabled
Python version: 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
ComfyUI version: 0.18.1
comfy-aimdo version: 0.2.12
comfy-kitchen version: 0.2.8
ComfyUI frontend version: 1.42.8
[Prompt Server] web root: O:\ComfyUI\comfyui\python\Lib\site-packages\comfyui_frontend_package\static
Asset seeder disabled
Skipping loading of custom nodes
Context impl SQLiteImpl.
Will assume non-transactional DDL.
Starting server

To see the GUI go to: http://127.0.0.1:8188
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by jaeone94**
## Summary

Muted and bypassed nodes are excluded from execution but were still triggering missing model/media/node warnings. This PR makes the error system mode-aware: muted/bypassed nodes no longer produce missing asset errors, and all error lifecycle events (mode toggle, deletion, paste, undo, tab switch) are handled consistently.

- Fixes Comfy-Org/ComfyUI#13256

## Behavioral notes

- **Tab switch overlay suppression (intentional)**: Switching back to a workflow with missing assets no longer re-shows the error overlay. This reverses the behavior introduced in #10190. The error state is still restored silently in the errors tab — users can access it via the properties panel without being interrupted by the overlay on every tab switch.

### 1. Scan filtering

- `scanAllModelCandidates`, `scanAllMediaCandidates`, `scanMissingNodes`: skip nodes with `mode === NEVER || BYPASS`
- `collectMissingNodes` (serialized data): skip error reporting for muted/bypassed nodes while still calling `sanitizeNodeName` for safe `configure()`
- `collectEmbeddedModelsWithSource`: skip muted/bypassed nodes; workflow-level `graphData.models` only create candidates when active nodes exist
- `enrichWithEmbeddedMetadata`: filter unmatched workflow-level models when all referencing nodes are inactive

### 2. Realtime mode change handling

- `useErrorClearingHooks.ts` chains `graph.onTrigger` to detect `node:property:changed` (mode)
- Deactivation (active → muted/bypassed): remove missing model/media/node errors for the node
- Activation (muted/bypassed → active): scan the node and add confirmed errors, show overlay
- Subgraph container deactivation: remove all interior node errors (execution ID prefix match)
- Subgraph container activation: scan all active interior nodes recursively
- Subgraph interior mode change: resolve node via `localGraph.getNodeById()` then compute execution ID from root graph

### 3. Node deletion

- `graph.onNodeRemoved`: remove missing model/media/node errors for the deleted node
- Handle `node.graph === null` at callback time by using `String(node.id)` for root-level nodes

### 4. Node paste/duplicate

- `graph.onNodeAdded`: scan via `queueMicrotask` (deferred until after `node.configure()` restores widget values)
- Guard: skip during `ChangeTracker.isLoadingGraph` (undo/redo/tab switch handled by pipeline)
- Guard: skip muted/bypassed nodes

### 5. Workflow tab switch optimization

- `skipAssetScans` option in `loadGraphData`: skip full pipeline on tab switch
- Cache missing model/media/node state per workflow via `PendingWarnings`
- `beforeLoadNewGraph`: save current store state to outgoing workflow's `pendingWarnings`
- `showPendingWarnings`: restore cached errors silently (no overlay), always sync missing nodes store (even when null)
- Preserve UI state (`fileSizes`, `urlInputs`) on tab switch by using `setMissingModels([])` instead of `clearMissingModels()`
- `MissingModelRow.vue`: fetch file size on mount via `fetchModelMetadata` memory cache

### 6. Undo/redo overlay suppression

- `silentAssetErrors` option propagated through pipeline → `surfaceMissingModels`/`surfaceMissingMedia` `{ silent }` option
- `showPendingWarnings` `{ silent }` option for missing nodes overlay
- `changeTracker.ts`: pass `silentAssetErrors: true` on undo/redo

### 7. Error tab node filtering

- Selected node filters missing model/media card contents (not just group visibility)
- `isAssetErrorInSelection`: resolve execution ID → graph node for selection matching
- Missing nodes intentionally unfiltered (pack-level scope)
- `hasMissingMediaSelected` added to `RightSidePanel.vue` error tab visibility
- Download All button: show only when 2+ downloadable models exist

### 8. New store functions

- `missingModelStore`: `addMissingModels`, `removeMissingModelsByNodeId`
- `missingMediaStore`: `addMissingMedia`, `removeMissingMediaByNodeId`
- `missingNodesErrorStore`: `removeMissingNodesByNodeId`
- `missingModelScan`: `scanNodeModelCandidates` (extracted single-node scan)
- `missingMediaScan`: `scanNodeMediaCandidates` (extracted single-node scan)

### 9. Test infrastructure improvements

- `data-testid` on `RightSidePanel.vue` tabs (`panel-tab-{value}`)
- Error-related TestIds moved from `dialogs` to `errorsTab` namespace in `selectors.ts`
- Removed unused `TestIdValue` type
- Extracted `cleanupFakeModel` to shared `ErrorsTabHelper.ts`
- Renamed `openErrorsTabViaSeeErrors` → `loadWorkflowAndOpenErrorsTab`
- Added `aria-label` to pencil edit button and subgraph toggle button

### Unit tests (41 new)

- Store functions: `addMissing*`, `removeMissing*ByNodeId`
- `executionErrorStore`: `surfaceMissing*` silent option
- Scan functions: muted/bypassed filtering, `scanNodeModelCandidates`, `scanNodeMediaCandidates`
- `workflowService`: `showPendingWarnings` silent, `beforeLoadNewGraph` caching

### E2E tests (17 new in `errorsTabModeAware.spec.ts`)

**Missing nodes**
- [x] Deleting a missing node removes its error from the errors tab
- [x] Undo after bypass restores error without showing overlay

**Missing models**
- [x] Loading a workflow with all nodes bypassed shows no errors
- [x] Bypassing a node hides its error, un-bypassing restores it
- [x] Deleting a node with missing model removes its error
- [x] Undo after bypass restores error without showing overlay
- [x] Pasting a node with missing model increases referencing node count
- [x] Pasting a bypassed node does not add a new error
- [x] Selecting a node filters errors tab to only that node

**Missing media**
- [x] Loading a workflow with all nodes bypassed shows no errors
- [x] Bypassing a node hides its error, un-bypassing restores it
- [x] Pasting a bypassed node does not add a new error
- [x] Selecting a node filters errors tab to only that node

**Subgraph**
- [x] Bypassing a subgraph hides interior errors, un-bypassing restores them
- [x] Bypassing a node inside a subgraph hides its error, un-bypassing restores it

**Workflow switching**
- [x] Does not resurface error overlay when switching back to workflow with missing nodes
- [x] Restores missing nodes in errors tab when switching back to workflow

# Screenshots

https://github.com/user-attachments/assets/e0a5bcb8-69ba-4120-ab7f-5c83e4cfc3c5

## Follow-up work

- Extract error-detection computed properties from `RightSidePanel.vue` into a composable (e.g. `useErrorsTabVisibility`)

### CODE REVIEW

File: src/scripts/app.ts [hunk 1]
```diff
@@ -1415,17 +1432,20 @@ export class ComfyApp {
...
 
-      await this.runMissingMediaPipeline()
+        await this.runMissingMediaPipeline(silentAssetErrors)
+      }
 
       if (!deferWarnings) {
-        useWorkflowService().showPendingWarnings()
+        useWorkflowService().showPendingWarnings(undefined, {
+          silent: silentAssetErrors
+        })
```
[the remark this answers is not in the document]
Comment (jaeone94) [reply src/scripts/app.ts:1452]: This concern is not applicable. The `skipAssetScans` flag is only set to `true` during tab switches to already-loaded workflows (`openWorkflow` in `workflowService.ts` sets `skipAssetScans: !loadFromRemote`).

The missing node cache is kept fresh by a different mechanism: `beforeLoadNewGraph()` (`workflowService.ts:366-413`) runs **before** every graph load and snapshots the current store state into `pendingWarnings`:

```ts
// workflowService.ts:392-406
const nodeTypes = missingNodesErrorStore.missingNodesError?.nodeTypes
activeWorkflow.pendingWarnings = {
  missingNodeTypes: nodeTypes?.length ? [...nodeTypes] : undefined,
  missingModelCandidates: ...,
  missingMediaCandidates: ...
}
```

So the flow for tab switches is:
1. **Leave workflow A**: `beforeLoadNewGraph()` caches A's current store state (including any resolved/new missing nodes)
2. **Load workflow B**: `skipAssetScans=true` skips the full pipeline
3. **Return to A**: `showPendingWarnings()` restores from the cache written in step 1

The cache in `runMissingModelPipeline` (lines 1511-1523) is only for the **initial load** path (`skipAssetScans=false`). For tab switches, `beforeLoadNewGraph` is the authoritative cache writer and it always reflects the latest store state.

**Comment by jaeone94** [comment]
Nodes in mute or bypass mode are now excluded from the "missing model" error, which causes some failures in the screenshot test. To resolve this, a new screenshot is captured.

File: src/composables/graph/useErrorClearingHooks.ts [hunk 2]
```diff
@@ -129,20 +288,54 @@ export function installErrorClearingHooks(graph: LGraph): () => void {
...
   graph.onNodeRemoved = function (node: LGraphNode) {
+    // node.graph is already null by the time onNodeRemoved fires,
+    // so use the graph that this hook is installed on to build the
+    // execution ID. Root-level nodes use their ID directly; subgraph
+    // interior nodes are handled by LGraph's recursive removal which
+    // calls onNodeRemoved on the subgraph's graph instance.
+    const execId =
+      graph === app.rootGraph
+        ? String(node.id)
+        : (getExecutionIdByNode(app.rootGraph, node) ?? String(node.id))
```
Comment (dante01yoon) [inline src/composables/graph/useErrorClearingHooks.ts]: Comment: When a node is removed from within the subgraph editor, node.graph is already null at callback time, so getExecutionIdByNode fails and falls back to String(node.id) (the local ID, e.g. "63") instead of the full execution path (e.g. "65:70:63"). This won't match stored execution IDs, so errors for that node won't be cleaned up. Consider caching the execution ID in a WeakMap at hook-install time.

File: src/platform/missingModel/components/MissingModelRow.vue [hunk 3]
```diff
@@ -244,6 +245,17 @@ const store = useMissingModelStore()
 const { selectedLibraryModel, importCategoryMismatch, urlInputs } =
   storeToRefs(store)
 
+onMounted(() => {
+  const url = model.representative.url
+  if (url && !store.fileSizes[url]) {
+    fetchModelMetadata(url).then((metadata) => {
```
Comment (dante01yoon) [inline src/platform/missingModel/components/MissingModelRow.vue]: Comment: Missing .catch() — if fetchModelMetadata rejects (network error), this is an unhandled rejection.

File: src/scripts/changeTracker.ts [hunk 4]
```diff
@@ -165,9 +165,8 @@ export class ChangeTracker {
       this._restoringState = true
       try {
         await app.loadGraphData(prevState, false, false, this.workflow, {
-          showMissingModels: false,
-          showMissingNodes: false,
-          checkForRerouteMigration: false
+          checkForRerouteMigration: false,
+          silentAssetErrors: true
```
Comment (dante01yoon) [inline src/scripts/changeTracker.ts:169]: Comment: Previously undo/redo skipped scans entirely (showMissingModels: false). Now it runs the full pipeline silently (no skipAssetScans). For large workflows this iterates all nodes/widgets + hits async verification. Was this intentional, or should undo/redo also use skipAssetScans: true and restore from cache like tab switches?

File: src/composables/graph/useErrorClearingHooks.ts [hunk 5]
```diff
@@ -121,6 +140,146 @@ function restoreNodeHooksRecursive(node: LGraphNode): void {
...
+  nodesStore.removeMissingNodesByNodeId(execId)
+
+  // For subgraph containers, also remove errors from interior nodes
+  if (node.isSubgraphNode?.() && node.subgraph) {
+    const prefix = `${execId}:`
+    for (const candidate of modelStore.missingModelCandidates ?? []) {
+      if (String(candidate.nodeId).startsWith(prefix)) {
+        modelStore.removeMissingModelsByNodeId(String(candidate.nodeId))
+      }
+    }
```
Comment (dante01yoon) [inline src/composables/graph/useErrorClearingHooks.ts]: Comment: This calls removeMissingModelsByNodeId N times for N candidates sharing the same node ID. Collect into a Set<string> first, then remove once per ID. Same pattern for the media and nodes loops below.

**Review by dante01yoon — COMMENTED** [review]
even excluding browser test, PR is quiet huge :)

**Comment by jaeone94** [comment]
Sorry for the huge PR 🥲

File: src/scripts/changeTracker.ts (hunk 4 above)
Comment (jaeone94) [reply src/scripts/changeTracker.ts:169]: Intentional. 
Tab switch and undo/redo are fundamentally different — tab switch restores the same workflow state that was last cached, but undo/redo navigates between graph snapshots that may have genuinely different missing-asset sets (e.g. user adds a node referencing a missing model, then undo removes it; or vice-versa). 

The current PendingWarnings cache is a single per-workflow slot and would produce incorrect results if reused for undo/redo.

Agreed that the full-pipeline cost is non-trivial for large workflows. A proper fix would attach a per-snapshot scan  cache to ChangeTracker's undo/redo queue entries — but as you noted this carries its own complexity (tracking restorable-vs-removed candidates, invalidation on graph mutations, memory).

I'll defer that to a follow-up PR rather than expanding this one's scope.

File: src/composables/graph/useErrorClearingHooks.ts (hunk 2 above)
Comment (jaeone94) [reply src/composables/graph/useErrorClearingHooks.ts]: Fixed in 815093221.

Added `getExecutionIdForNodeInGraph(rootGraph, graph, nodeId)` in `graphTraversalUtil.ts` which derives the execution ID from the `(graph, nodeId)` pair without relying on `node.graph`. The `onNodeRemoved` hook now uses it via the closure-captured `graph` reference, producing the full `parentId:...:nodeId` path even after LiteGraph nulls `node.graph` (`LGraph.ts:1112` runs before `this.onNodeRemoved` at `:1132`).

Coverage:
- Unit: `graphTraversalUtil.test.ts` — "works when node is detached (node.graph = null)" and 5 other helper cases
- Unit: `useErrorClearingHooks.test.ts` — calls real `subgraph.remove(interiorNode)` and asserts the missing model/media/nodes stores are cleared at the `parentId:nodeId` key
- E2E: `errorsTabModeAware.spec.ts` — added two "Deleting a node inside a subgraph removes its missing X error" cases under the Subgraph block

File: src/platform/missingModel/components/MissingModelRow.vue (hunk 3 above)
Comment (jaeone94) [reply src/platform/missingModel/components/MissingModelRow.vue]: Fixed in a36aff97d. Added `.catch` with `console.warn` so a transient metadata fetch failure no longer surfaces as an unhandled rejection. Verified the cleanup path in `fetchModelMetadata` (`missingModelDownload.ts:178-182`) — the inflight entry is removed in `finally` and the cache is only set on `isComplete`, so failed fetches don't poison either map.

File: src/composables/graph/useErrorClearingHooks.ts (hunk 5 above)
Comment (jaeone94) [reply src/composables/graph/useErrorClearingHooks.ts]: Refactored in a36aff97d (and hardened in 197c85f02).

Each missing-asset store now exposes `removeMissing*ByPrefix(prefix)` which performs a single-pass filter, preserves the existing interaction-state cleanup semantics (only clear when no remaining candidate uses the same name), and ignores nullish nodeIds. The hook calls each store once with `${execId}:` instead of iterating candidates externally.

The trailing colon in the prefix is load-bearing — it prevents sibling IDs sharing a numeric prefix (e.g. `"705"` vs `"70"`) from being matched. JSDoc on each method makes the convention explicit, and unit tests cover the sibling-collision guard plus deeply-nested interior cleanup.

**Review by dante01yoon — COMMENTED** [review]
Still seeing a few correctness issues on the latest head:

1. `src/scripts/app.ts:1147`, `:1527`, `:1650`
The tab-switch path now uses `setMissingModels([])` / `setMissingMedia([])` instead of `clearMissing*()`. That preserves UI state, but it also means the previous workflow's verification controllers are not aborted. If workflow A has an in-flight missing-asset verification and I switch to workflow B with `skipAssetScans: true`, the late result from A can still come back and repopulate the global missing-model/media stores while B is active.

2. `src/composables/graph/useErrorClearingHooks.ts:164`
The realtime add/un-bypass path only adds candidates where `isMissing === true`. That works in OSS, but in cloud mode the per-node scanners intentionally leave candidates unresolved until async verification (`src/platform/missingModel/missingModelScan.ts:174`, `src/platform/missingMedia/missingMediaScan.ts:89`). So pasted or re-activated cloud nodes with missing assets won't surface here until the next full workflow scan.

3. `src/platform/missingModel/missingModelScan.ts:229`
The workflow-level embedded-model suppression still looks too coarse. `hasActiveNodes` only checks whether there is any active node somewhere in the workflow, not whether any active node actually references the embedded model. In a mixed workflow, a bypassed loader can still produce a missing-model row as long as some unrelated node is active.

**Comment by jaeone94** [comment]
@dante01yoon Thanks for the thorough review. All three correctness issues addressed:

**1. `app.ts:1147` — verification controller leak on tab switch**

Fixed in 5ff1c43a3. `skipAssetScans` path now calls `createVerificationAbortController().abort()` on both model and media stores before `setMissing*([])`, so a late result from workflow A can't repopulate the stores after switching to workflow B.

**2. `useErrorClearingHooks.ts:164` — cloud `isMissing === undefined` dropped in realtime scan**

Fixed in 5ff1c43a3. `scanSingleNodeErrors` now separates candidates into confirmed and pending, adds confirmed immediately, and fires `verifyAssetSupportedCandidates` / `verifyCloudMediaCandidates` for pending (fire-and-forget, silent error on failure). Once verification resolves, confirmed entries are added to the store. Mirrors the full pipeline pattern in `runMissingModelPipeline`.

Verified locally in cloud mode: bypass → un-bypass cycle on CheckpointLoader (missing model) and LoadImage (missing media) now restores the errors tab entries; previously only missing-node-type returned.

3 unit tests added in `useErrorClearingHooks.test.ts` covering: pending model surfaces after verification, pending media surfaces after verification, confirmed-present candidates are not added.

**3. `missingModelScan.ts:229` — `hasActiveNodes` too coarse**

Fixed in 56fc54484. Replaced the global `hasActiveNodes` check with `isModelReferencedByActiveNode(modelName, allNodes)` — a per-model scan over active nodes' widget values and `node.properties.models`. Workflow-level entries now survive only when an active node actually references the model by name.

2 unit tests added in `missingModelScan.test.ts` covering: stale workflow-level entry dropped when only bypassed node references it (other active nodes present); node-sourced unmatched entries preserved in mixed graphs.

Not fixing the broader question of whether the workflow-level `graphData.models` "creates new candidate" path is needed at all in production (given `scanAllModelCandidates` is now always called) — leaving that as a follow-up investigation since it touches a legacy OSS dialog contract.

**Review by dante01yoon — COMMENTED** [review]
Still seeing one remaining correctness issue on the latest head:

`src/composables/graph/useErrorClearingHooks.ts:191-205` and `:231-249`

The new cloud-mode realtime fix still fires async verification as fire-and-forget. `scanSingleNodeErrors()` starts `verifyAndAddPendingModels()` / `verifyAndAddPendingMedia()`, but those helpers do not carry an `AbortSignal` and do not re-check whether the node is still active/present/current when verification finishes.

That means a late verification result can still re-add stale missing-asset entries after the node has been bypassed again, deleted, or the user has switched workflows.

I confirmed this on the current head with a small Vitest repro: un-bypass a cloud-backed missing-model node, immediately bypass it again before verification resolves, and the missing-model entry still gets re-added to the store.

I think this needs the same kind of cancellation / staleness guard that the full-pipeline path now has in `app.ts`.

**Comment by jaeone94** [comment]
@dante01yoon Good catch — fixed in 799680c23.

Added `isCandidateStillActive(nodeId)` that re-resolves the candidate's node in the current `app.rootGraph` via `getNodeByExecutionId` and requires it to be present and not muted/bypassed. Applied in both `verifyAndAddPendingModels` and `verifyAndAddPendingMedia` before the store add.

A single staleness predicate covers all three late-result scenarios:
- **Bypass race**: `node.mode` is BYPASS/NEVER when verification resolves → drop
- **Delete race**: `getNodeByExecutionId` returns null → drop
- **Workflow switch**: `app.rootGraph` points to a different workflow so the old execId doesn't resolve → drop

Chose a result-time staleness check rather than an `AbortController` because reusing the store's controller (as the full pipeline does) would cancel each other's work, and introducing a separate per-call controller adds lifecycle management without additional safety — the staleness predicate already catches the cases the abort would.

Two new Vitest cases in `useErrorClearingHooks.test.ts` using a blocked verification promise:
- `skips adding verified model when node was bypassed before verification resolved`
- `skips adding verified media when node is deleted before verification resolved`

**Review by dante01yoon — APPROVED** [review]
Verified file passes for review. I ddin't spot other new issues in latest folloup commits . Thanks for the hard work!

**Comment by jaeone94** [comment]
Thank you so much for continuing to review my work.
Next time, I’ll break it down into smaller PRs. It’s taken me a while to learn this lesson.
