### PR TITLE
[bugfix] Filter model metadata by current widget selection

### LINKED ISSUE #3664: [Bug]: Model metadata stays after changing workflow models
### Frontend Version

1.17.1

### Expected Behavior

Changing the model on a node then saving should remove the model metadata.

### Actual Behavior

The model metadata stays with the older model. Then when reloading, it prompts to download a model which is no longer relevant to the workflow.

### Steps to Reproduce

1. Load a template workflow
2. Change the model in a node that has model metadata in it (can check by clicking "Properties" in the node's right-click context menu.
3. Save the worfklow
4. Close then reload the workflow
5. Observe that the missing models dialog prompts you to download a model that is no longer being used in the workflow 

### Debug Logs

```powershell
N/A
```

### Browser Logs

N/A

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/19933834/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

### Other Information

_No response_

### PR DESCRIPTION
**Pull request by christian-byrne**
Filter models in workflow metadata to only include those actually selected in node widgets. Prevents false positives in the missing models dialog when nodes contain outdated metadata.

Fixes #3664

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-4021-bugfix-Filter-model-metadata-by-current-widget-selection-2036d73d365081bdb416c3c3f584d4a4) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/scripts/app.ts [hunk 1]
```diff
@@ -1037,8 +1038,10 @@ export class ComfyApp {
       }
 
       // Collect models metadata from node
-      if (n.properties?.models?.length)
-        embeddedModels.push(...n.properties.models)
+      const selectedModels = getSelectedModelsMetadata(n)
+      if (selectedModels && selectedModels.length > 0) {
```
Comment (webfiltered) [inline src/scripts/app.ts]:
```suggestion
      if (selectedModels?.length) {
```

File: src/utils/modelMetadataUtil.ts [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+ * @returns Filtered array containing only models that are currently selected
+ */
+export function getSelectedModelsMetadata(node: {
+  type: string
+  widgets_values?: unknown[] | Record<string, unknown>
+  properties?: { models?: ModelFile[] }
+}): ModelFile[] {
+  try {
+    if (!node.properties?.models?.length) return []
+    if (!node.widgets_values) return []
```
Comment (webfiltered) [inline src/utils/modelMetadataUtil.ts]:
```suggestion
    if (!node.properties?.models?.length) return
    if (!node.widgets_values) return
```

File: src/utils/modelMetadataUtil.ts [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+    const widgetValues = Array.isArray(node.widgets_values)
+      ? node.widgets_values
+      : Object.values(node.widgets_values)
+
+    if (!widgetValues.length) return []
```
Comment (webfiltered) [inline src/utils/modelMetadataUtil.ts]:
```suggestion
    if (!widgetValues.length) return
```

File: src/utils/modelMetadataUtil.ts [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+      }
+    }
+
+    // Return the node's models that are present in the widget values
+    return node.properties.models.filter((model) =>
+      stringWidgetValues.has(model.name)
+    )
+  } catch (error) {
+    console.error('Error filtering models by current selection:', error)
+    return []
```
Comment (webfiltered) [inline src/utils/modelMetadataUtil.ts]:
```suggestion
```

File: src/utils/modelMetadataUtil.ts [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+ * ```
+ *
+ * @param node - The workflow node to process
+ * @returns Filtered array containing only models that are currently selected
+ */
+export function getSelectedModelsMetadata(node: {
+  type: string
+  widgets_values?: unknown[] | Record<string, unknown>
+  properties?: { models?: ModelFile[] }
+}): ModelFile[] {
```
Comment (webfiltered) [inline src/utils/modelMetadataUtil.ts]:
```suggestion
}): ModelFile[] | undefined {
```

**Review by webfiltered — COMMENTED** [review]
This is really just one suggested change.

"Simplify code using idiomatic undefined"

File: src/utils/modelMetadataUtil.ts (hunk 5 above)
Comment (christian-byrne) [reply src/utils/modelMetadataUtil.ts]: Thanks!

**Comment by christian-byrne** [comment]
Changes:

- Simplify code using idiomatic undefined
- Updated unit test expectations to expect `undefined` rather than empty array to match above change

**Review by webfiltered — APPROVED** [review]
Will merge into 1.22
