### PR TITLE
Ignore reserved keybindings when typing in text input

### LINKED ISSUE #2476: [Bug]: Keybindings that use shift modifer will activate when typing in setting search
### Frontend Version

1.9.6

### Expected Behavior

When typing in the settings search, I would not expect keybindings to activate.

### Actual Behavior

When typing in the settings dialog search bar, keybindings activate inadvertantly, running the associated command in the background.

### Steps to Reproduce

1. Open settings dialog
2. Go to the `Keybindings` panel
3. Bind a common key sequence with the shift modifier like `Shift`+`n` to some command like `New Blank Workflow`
4. Confirm the new keybinding
5. Focus the settings search box
6. Type the command
7. Observe the command activates

### Browser Logs

```
client:495 [vite] connecting...
19:28:16.545 client:614 [vite] connected.
19:28:16.704 api.ts:170 Running on localhost:5173
19:28:16.756 App.vue:44 ComfyUI Front-end version: 1.9.6
19:28:16.758 pinia.mjs:267 🍍 "user" store installed 🆕
19:28:16.874 pinia.mjs:267 🍍 "queuePendingTaskCount" store installed 🆕
19:28:16.874 pinia.mjs:267 🍍 "queueSettingsStore" store installed 🆕
19:28:16.874 pinia.mjs:267 🍍 "execution" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "queue" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "keybinding" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "command" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "menuItem" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "canvas" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "workflowBookmark" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "workflow" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "modelToNode" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "extension" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "titleEditor" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "searchBox" store installed 🆕
19:28:16.875 pinia.mjs:267 🍍 "sidebarTab" store installed 🆕
19:28:16.949 extensionStore.ts:64 Extension Comfy.EditAttention is disabled.
19:28:16.955 pinia.mjs:267 🍍 "widget" store installed 🆕
19:28:17.173 workflowStore.ts:76 load and start tracking of workflow workflows/Unsaved Workflow (75).json
19:28:17.173 workflowStore.ts:265 [workflowStore] open workflow workflows/Unsaved Workflow (75).json
19:28:17.280 pinia.mjs:267 🍍 "serverConfig" store installed 🆕
19:28:17.280 pinia.mjs:267 🍍 "models" store installed 🆕
19:28:17.280 pinia.mjs:267 🍍 "nodeFrequency" store installed 🆕
19:28:17.778 runtime-core.esm-bundler.js:7013 <Suspense> is an experimental feature and its API will likely change.
19:28:17.830 pinia.mjs:267 🍍 "systemStats" store installed 🆕
19:28:17.830 pinia.mjs:267 🍍 "aboutPanel" store installed 🆕
19:28:20.043 localhost/:1 Autofocus processing was blocked because a document already has a focused element.
19:28:33.460 workflowStore.ts:76 load and start tracking of workflow workflows/Unsaved Workflow (73).json
19:28:33.460 workflowStore.ts:265 [workflowStore] open workflow workflows/Unsaved Workflow (73).json
```

### Setting JSON

[comfy.settings.json](https://github.com/user-attachments/files/18722917/comfy.settings.json)

### What browsers do you use to access the UI ?

Google Chrome

### Other

_No response_

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2476-Bug-Keybindings-that-use-shift-modifer-will-activate-when-typing-in-setting-search-1956d73d3650815fa35afd85e67d2b6a) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by christian-byrne**
Fixes #2476.

While there is an ongoing effort to implement keybinding contexts ([#1595](https://github.com/Comfy-Org/ComfyUI_frontend/issues/1595), [#1089](https://github.com/Comfy-Org/ComfyUI_frontend/issues/1089)), this particular check wouldn't integrate neatly into that system: (1) It doesn't rely on element IDs, (2) it's affecting key combos rather than commands, (3) it's preventing keybindings rather than selectively enabling them.

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-2514-Ignore-reserved-keybindings-when-typing-in-text-input-1976d73d36508194a247f25b8c826936) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/constants/reservedKeyCombos.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+  'Shift + ArrowLeft',
+  'Ctrl + Shift + ArrowLeft',
+  'ArrowRight',
+  'Ctrl + ArrowRight',
+  'Shift + ArrowRight',
+  'Ctrl + Shift + ArrowRight',
+  'ArrowUp',
+  'Shift + ArrowUp',
+  'ArrowDown',
+  'Shift + ArrowDown'
```
Comment (christian-byrne) [inline src/constants/reservedKeyCombos.ts:34]: Ctrl+ArrowUp and Ctrl+ArrowDown in textareas are used by edit attention extension.

File: src/constants/reservedKeyCombos.ts [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+  'Enter',
+  'Shift + Enter',
+  'Ctrl + Backspace',
+  'Ctrl + Delete',
+  'Home',
+  'Ctrl + Home',
+  'Ctrl + Shift + Home',
+  'End',
+  'Ctrl + End',
+  'Ctrl + Shift + End',
```
Comment (webfiltered) [inline src/constants/reservedKeyCombos.ts:18]:
```suggestion
  'Ctrl + Shift + End',
  'PageUp',
  'PageDown',
  'Shift + PageUp',
  'Shift + PageDown',
```

**Review by webfiltered — COMMENTED** [review]
Should add meta-key in, if it's not being normalised to Ctrl (which.. it probably should not be).

Not really in the scope of the PR, but.. if we are acting on event bubble (not capture), it would be ideal to just have a shared function added as a listener on text inputs - and it could simply prevent bubbling.

That would let our future-key-combo-manager normally operate on bubble, and use capture for special situations.

**Comment by christian-byrne** [comment]
> Should add meta-key in, if it's not being normalised to Ctrl (which.. it probably should not be).

It's being normalized

https://github.com/Comfy-Org/ComfyUI_frontend/blob/29cd6933359b9d1eb4bc87ecf47b8632cfb8e252/src/stores/keybindingStore.ts#L43-L46
 
> Not really in the scope of the PR, but.. if we are acting on event bubble (not capture), it would be ideal to just have a shared function added as a listener on text inputs - and it could simply prevent bubbling.
> 
> That would let our future-key-combo-manager normally operate on bubble, and use capture for special situations.

Is there an efficient way to keep track of all text inputs? I still want to hold out hope for a very performant solution that just maps element IDs to commands.

**Comment by webfiltered** [comment]
> efficient way to keep track of all text inputs

As long as you're adding the _same_ function as an event listener, you can do it to thousands of elements and it won't matter.  Preferred, even.  And only one element is going to call it at a time, anyway.

On the other hand, if you're adding a new arrow func every time, that's going to be less efficient - but unless the code is truly awful, it'll be hard to notice.

**Review by huchenlei — APPROVED** [review]
LGTM. We can discuss the context aware keybinding impl in a separate PR.
