### PR TITLE
Fix: latent preview format is read from wrong byte of header

### LINKED ISSUE #3545: [Bug]: Image blobs created via socket API always set to JPEG MIME type
### Frontend Version

1.17.4

### Expected Behavior

Blobs created via API socket have correct MIME type.

### Actual Behavior

All blobs are created with `image/jpeg` MIME type.

### Steps to Reproduce

-

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

### What browsers do you use to access the UI ?

_No response_

### Other Information

`view` and `view2` both reference the same `DataView`.  `view2` likely should be created on `buffer` insteead.
https://github.com/Comfy-Org/ComfyUI_frontend/blob/53ee5904e8293bdcc575a61d7a4c01552c65fdb8/src/scripts/api.ts#L367-L373

Reported by blepping? on Discord, who also offered this as a workaround to allow passing any MIME type:

```diff
diff --git a/src/scripts/api.ts b/src/scripts/api.ts
index 548d98d4..f81ba6ff 100644
--- a/src/scripts/api.ts
+++ b/src/scripts/api.ts
@@ -314,23 +314,35 @@ export class ComfyApi extends EventTarget {
     this.socket.addEventListener('message', (event) => {
       try {
         if (event.data instanceof ArrayBuffer) {
-          const view = new DataView(event.data)
+          const buffer = event.data
+          const view = new DataView(buffer)
           const eventType = view.getUint32(0)
-          const buffer = event.data.slice(4)
+          let buff_offset = 4
           switch (eventType) {
             case 1:
-              const view2 = new DataView(event.data)
-              const imageType = view2.getUint32(0)
+              const imageType = view.getUint32(buff_offset)
+              buff_offset += 4
               let imageMime
               switch (imageType) {
                 case 1:
-                default:
                   imageMime = 'image/jpeg'
                   break
                 case 2:
                   imageMime = 'image/png'
+                  break
+                case 3:
+                  const td = new TextDecoder('utf-8')
+                  const mime_type_len = view.getUint8(buff_offset)
+                  buff_offset++
+                  imageMime = td.decode(buffer.slice(buff_offset, buff_offset + mime_type_len))
+                  buff_offset += mime_type_len
+                  break
+                default:
+                  throw new Error(
+                    `Unknown binary websocket image type ${imageType} for message of type ${eventType}`
+                  )
               }
-              const imageBlob = new Blob([buffer.slice(4)], {
+              const imageBlob = new Blob([buffer.slice(buff_offset)], {
                 type: imageMime
               })
               this.dispatchCustomEvent('b_preview', imageBlob)
```

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-3545-Bug-Image-blobs-created-via-socket-API-always-set-to-JPEG-MIME-type-1dc6d73d365081c49f72c04e0acbcc20) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by christian-byrne**
Fixes parsing image type from binary preview messages. Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/3545

Preview image headers follow format:

```
[ First 4 bytes: event type ] [ Next 4 bytes: image format ] [ Remaining bytes: image data ]
```

The code currently reads event type and image format from the same dword, which is obviously wrong.

To verify, you can repro a bug by doing:

1. Change [this code](https://github.com/Comfy-Org/ComfyUI-private/blob/master/latent_preview.py#L92) to send png images as latent previews
2. Start ComfyUI and specify a preview method like `--preview-method taesd`
3. Open the default workflow, replace the `SaveImage` node with a `SaveImageWebSocket` node
4. Open Network panel, go to `WS`, find the binary event messages and read the header in hex editor. Or just right click on the preview images and try to save and see the file extension

### Background

Process for sending latent previews from the server:

1. `latent_preview.py` module decodes latent using user's specified preview-method then adds the decoded latent and its format into message queue using [`send_sync`](https://github.com/Comfy-Org/ComfyUI-private/blob/master/server.py#L820-L822)
5. [`hijack_progress`](https://github.com/Comfy-Org/ComfyUI-private/blob/master/main.py#L229-L239) processes the message and adds back to queue, specifying the message type (binary unencoded preview)
6. [`publish_loop`](https://github.com/Comfy-Org/ComfyUI-private/blob/master/server.py#L827-L830) pops message and passes to `PromptServer`'s [`send`](https://github.com/Comfy-Org/ComfyUI-private/blob/master/server.py#L759-L761) which checks that the message is of type `BinaryEventTypes.UNENCODED_PREVIEW_IMAGE` and then passes the message to [`send_image`](https://github.com/Comfy-Org/ComfyUI-private/blob/master/server.py#L776-L798), which prepends a dword to the data to indicate the type (1 = jpeg, 2 = png).
7. `send_image` encodes the image in the given format using PIL then calls [`send_bytes`](https://github.com/Comfy-Org/ComfyUI-private/blob/master/server.py#L800-L808) which [prepends another dword indicating the event type](https://github.com/Comfy-Org/ComfyUI-private/blob/master/server.py#L767-L774) (in this case, `1` to denote `BinaryEventTypes.PREVIEW_IMAGE`
8. `send_bytes` sends the data to all attached WS sockets

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-3761-Fix-latent-preview-format-is-read-from-wrong-byte-of-header-1ea6d73d3650817ba58ecc70e9b5f0e9) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by webfiltered** [comment]
Does this resolve:

- #3545

File: src/scripts/api.ts [hunk 1]
```diff
@@ -380,19 +380,20 @@ export class ComfyApi extends EventTarget {
         if (event.data instanceof ArrayBuffer) {
           const view = new DataView(event.data)
           const eventType = view.getUint32(0)
+          const imageType = view.getUint32(4)
           const buffer = event.data.slice(4)
```
Comment (webfiltered) [inline src/scripts/api.ts]: Removing `view2`, it looks like this one is now redundant.

Comment (christian-byrne) [reply src/scripts/api.ts]: which one?

**Comment by christian-byrne** [comment]
> * blobs created via socket API always set to JPEG MIME type #3545

Wow, so Blepping already found this bug before and found a fix as well.

Yes I believe this should close that issue. Right now it only benefits extensions, as ComfyUI Prompt server is only ever sending "JPEG", but perhaps this will become configurable in the future.

File: src/scripts/api.ts (hunk 1 above)
Comment (webfiltered) [reply src/scripts/api.ts]: Err sorry.. GH is being selective about what it displays... and this was just a minor cleanup nit..

```ts
const buffer = event.data.slice(4)
// ... was supposed to be used here, now has single ref a little later:
const imageBlob = new Blob([buffer.slice(4)], {
```

Comment (christian-byrne) [reply src/scripts/api.ts]: Oh, so remove the `buffer` variable and then change the offset in the second slice to `8`? Sounds good.

File: src/scripts/api.ts [hunk 2]
```diff
@@ -84,7 +84,7 @@ interface BackendApiCalls {
   execution_interrupted: ExecutionInterruptedWsMessage
   execution_cached: ExecutionCachedWsMessage
   logs: LogsWsMessage
-  /** Mr Blob Preview, I presume? */
```
Comment (webfiltered) [inline src/scripts/api.ts:87]: Taking this opportunity to express my profound sadness at the removal of "Mr Blob Preview" from the repo. 😢

**Review by webfiltered — APPROVED** [review]

**Comment by blepping** [comment]
> Yes I believe this should close that issue. Right now it only benefits extensions, as ComfyUI Prompt server is only ever sending "JPEG", but perhaps this will become configurable in the future.

Is there interest in making in configurable? I actually implemented frontend and server-side support for a third image type that allows sending the MIME type in the message (has a length byte + utf8 string containing the mime type). I was trying to get animated previews to work by pushing types like animated GIF/PNG/WEBM whatever, unfortunately the frontend just wouldn't actually play them so I kind of gave up. Having the ability to push stuff other than JPEG to the frontend seems like it could be useful though.

**Comment by christian-byrne** [comment]
Definitely, that's a great idea. Btw @blepping thank you for finding this issue, sorry I never saw the original issue.

I think we should support more mime types for both:

- "latent preview" messages that happening during a node's execution and are sent via progress bar hook (topic of this PR) and 
- node output previews that are sent after the node execution finishes

This biggest priority right now is actually text previews, for streaming LLM response. Would really like to get this added ASAP but no one working on it quite yet.

The things I'm curious about:

- For animated previews that you mention, is that for progress previews that happen mid-exeuction, or post-node-execution outputs? If the former, how does it work exactly and what type of node would it be using that?
- Would it be possible to do this without changing the the format (e.g., still just using 2 byes to map to formats)? There are defnitely a lot of apps expecting this message format that are not using ComfyUI_frontend.
- Any specific ideas or request for how you would like the API to be?

**Comment by blepping** [comment]
> For animated previews that you mention, is that for progress previews that happen mid-exeuction

Yes, progress previews that happen mid-execution. The main use case is for previewing video model generations. Not sure if you're already aware of it, but the VHS nodes do have that feature: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite — however there's a lot of complicated JS stuff for sending the messages. It also had to override the normal previewing stuff on the JS side which caused issues (at least when I used it, may be fixed now).

So if that exists, why do I want to make my own version? Partially because I just wanted to do it a cleaner way, but _mostly_ because that (and ComfyUI in general) only supports latent2RGB video latent previewing. madebyollin (same guy that made TAESD) has a series of equivalent models for previewing videos so there's a practical way to get much higher-quality previews. I already have the model/decoding/backend previewing to image (or animated image/video format) implemented in my Bleh node pack: https://github.com/blepping/ComfyUI-bleh#blehtaevideoencode-and-blehtaevideodecode

> Would it be possible to do this without changing the the format (e.g., still just using 2 byes to map to formats)? 

Yes (if I understand the question correctly). The way I did it was to add a third message type. If a JPEG looks like:

`| image_type[u8] | blob_len[u32] | blob[...] |`

My added image type `3` message looks like:

`| image_type[u8] | mime_type_len[u8] | mime_type[...] | blob_len[u32] | blob[...] |`

Since it's pretty short, I can just show you the way I had it implemented. This is just a sketch for the approach I used (and also vs an older frontend version, think the backend side still applies cleanly). I didn't take the time to polish it.

## Frontend

```diff
diff --git a/src/scripts/api.ts b/src/scripts/api.ts
index 548d98d4..f81ba6ff 100644
--- a/src/scripts/api.ts
+++ b/src/scripts/api.ts
@@ -314,23 +314,35 @@ export class ComfyApi extends EventTarget {
     this.socket.addEventListener('message', (event) => {
       try {
         if (event.data instanceof ArrayBuffer) {
-          const view = new DataView(event.data)
+          const buffer = event.data
+          const view = new DataView(buffer)
           const eventType = view.getUint32(0)
-          const buffer = event.data.slice(4)
+          let buff_offset = 4
           switch (eventType) {
             case 1:
-              const view2 = new DataView(event.data)
-              const imageType = view2.getUint32(0)
+              const imageType = view.getUint32(buff_offset)
+              buff_offset += 4
               let imageMime
               switch (imageType) {
                 case 1:
-                default:
                   imageMime = 'image/jpeg'
                   break
                 case 2:
                   imageMime = 'image/png'
+                  break
+                case 3:
+                  const td = new TextDecoder('utf-8')
+                  const mime_type_len = view.getUint8(buff_offset)
+                  buff_offset++
+                  imageMime = td.decode(buffer.slice(buff_offset, buff_offset + mime_type_len))
+                  buff_offset += mime_type_len
+                  break
+                default:
+                  throw new Error(
+                    `Unknown binary websocket image type ${imageType} for message of type ${eventType}`
+                  )
               }
-              const imageBlob = new Blob([buffer.slice(4)], {
+              const imageBlob = new Blob([buffer.slice(buff_offset)], {
                 type: imageMime
               })
               this.dispatchCustomEvent('b_preview', imageBlob)
```

## Backend

```diff
diff --git a/server.py b/server.py
index 76a99167..d864bae9 100644
--- a/server.py
+++ b/server.py
@@ -2,6 +2,7 @@ import os
 import sys
 import asyncio
 import traceback
+import mimetypes
 
 import nodes
 import folder_paths
@@ -769,15 +770,27 @@ class PromptServer():
                 resampling = Image.ANTIALIAS
 
             image = ImageOps.contain(image, (max_size, max_size), resampling)
-        type_num = 1
+
         if image_type == "JPEG":
             type_num = 1
         elif image_type == "PNG":
             type_num = 2
+        else:
+            type_num = 3
 
         bytesIO = BytesIO()
-        header = struct.pack(">I", type_num)
-        bytesIO.write(header)
+        bytesIO.write(struct.pack(">I", type_num))
+
+        if type_num == 3:
+            mime_type = mimetypes.guess_type(f"file.{image_type}")[0]
+            if mime_type is None:
+                raise RuntimeError(f"Could not look up MIME type for custom image type {image_type}")
+            mime_type = bytes(mime_type, encoding="utf-8")
+            if not 0 < len(mime_type) < 256:
+                raise RuntimeError(f"Could not handle unexpectedly long MIME type for custom image type {image_type}")
+            bytesIO.write(struct.pack("B", len(mime_type)))
+            bytesIO.write(mime_type)
+
         image.save(bytesIO, format=image_type, quality=95, compress_level=1)
         preview_bytes = bytesIO.getvalue()
         await self.send_bytes(BinaryEventTypes.PREVIEW_IMAGE, preview_bytes, sid=sid)
```

***

It seemed like it worked in my testing. I had debug code in the JS side that dumped stuff about the messages it was getting.

Is discussing this here fine, or should we move to a dedicated discussion/issue/whatever? I am also on Discord.
