### PR TITLE
fix: Improve legacy widget compatibility in vueNodes mode

### LINKED ISSUE #7615: Nodes 2.0 break Mask Rect Area node canvas
### Prerequisites

- [x] I am running the latest version of ComfyUI
- [x] I have searched existing issues to make sure this isn't a duplicate
- [x] I have tested with all custom nodes disabled ([see how](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled))

### What happened?

Whenever Nodes 2.0 is enabled, the ComfyUI-Impact-Pack [Mask Rect Area nodes](https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/861) no longer show the preview canvas.

### Steps to Reproduce

1. Install ImpactPack
2. Add Mask Rect Area node
3. Enable nodes 2.0

### How is this affecting you?

Visual/UI issue only

### ComfyUI Frontend Version

1.34.9

### Browser

Firefox

### Console Errors

```javascript

```

### Logs

```shell

```

### Additional Context

Image

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-7615-Nodes-2-0-break-Mask-Rect-Area-node-canvas-2cd6d73d365081f5b943ca60c2a7e817) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jtydhr88**
## Summary
- Fix widget callback signature to pass node as 3rd parameter for extensions like Impact Pack
- Add triggerDraw call to update all legacy widgets when any widget value changes
- Support computeLayoutSize for dynamic widget height calculation
- Set node.canvasHeight for extensions that rely on this property
- Use step/10 for number input buttons to match litegraph behavior

Fixes display and interaction issues with Impact Pack's Mask Rect Area nodes.

fix https://github.com/Comfy-Org/ComfyUI_frontend/issues/7615 and https://github.com/Comfy-Org/ComfyUI_frontend/issues/7616

it also requires Impact pack PR https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/1167

## Screenshots
Before

https://github.com/user-attachments/assets/eb890f7c-c1a0-4c7b-a8d7-dde304de83e4

After

https://github.com/user-attachments/assets/dad65b52-d71e-4c19-92c0-367b7dcafed0

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-7766-fix-Improve-legacy-widget-compatibility-in-vueNodes-mode-2d56d73d365081b18d83f4a41ff0f377) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by christian-byrne — COMMENTED** [review]
LGTM

File: src/composables/graph/useGraphNodeManager.ts [hunk 1]
```diff
@@ -171,7 +173,12 @@ export function safeWidgetMapper(
       const callback = (v: unknown) => {
         const value = normalizeWidgetValue(v)
         widget.value = value ?? undefined
-        widget.callback?.(value)
+        // Match litegraph callback signature: (value, canvas, node, pos, event)
+        // Some extensions (e.g., Impact Pack) expect node as the 3rd parameter
+        widget.callback?.(value, app.canvas, node)
+        // Trigger redraw for all legacy widgets on this node (e.g., mask preview)
+        // This ensures widgets that depend on other widget values get updated
+        node.widgets?.forEach((w) => w.triggerDraw?.())
```
Comment (AustinMroz) [inline src/composables/graph/useGraphNodeManager.ts:181]: Does this line ever actually make a difference?

This `callback` is exclusively used on the vue side when `@update:modelValue` is emitted, but WidgetLegacy never emits (or defines a model) because all the values are tracked on the litegraph side.

**Review by AustinMroz — APPROVED** [review]

File: src/renderer/extensions/vueNodes/components/NodeWidgets.vue [hunk 2]
```diff
@@ -203,10 +203,13 @@ const processedWidgets = computed((): ProcessedWidget[] => {
 })
 
 const gridTemplateRows = computed((): string => {
-  const widgets = toValue(processedWidgets)
-  return widgets
-    .filter((w) => !w.simplified.options?.hidden)
-    .map((w) => (shouldExpand(w.type) ? 'auto' : 'min-content'))
+  if (!nodeData?.widgets) return ''
+  const processedNames = new Set(toValue(processedWidgets).map((w) => w.name))
+  return nodeData.widgets
```
Comment (DrJKL) [inline src/renderer/extensions/vueNodes/components/NodeWidgets.vue:208]: This logic should be order dependent. You should be able to test it with a subgraph that contains multiple of the same type of node with the same widget promoted.

File: src/renderer/extensions/vueNodes/widgets/components/WidgetLegacy.vue [hunk 3]
```diff
@@ -52,9 +53,19 @@ onBeforeUnmount(() => {
...
+  if (widgetInstance.computedHeight) {
+    height = widgetInstance.computedHeight
+  } else if (widgetInstance.computeLayoutSize) {
+    height = widgetInstance.computeLayoutSize(node).minHeight
+  } else if (widgetInstance.computeSize) {
+    height = widgetInstance.computeSize(width)[1]
+  }
+  containerHeight.value = height
+  // Set node.canvasHeight for legacy widgets that use it (e.g., Impact Pack)
+  // @ts-expect-error canvasHeight is a custom property used by some extensions
```
Comment (DrJKL) [inline src/renderer/extensions/vueNodes/widgets/components/WidgetLegacy.vue:67]: Can you augment the type instead of adding a suppression?

**Comment by jtydhr88** [comment]
FYI, as one contributor from impact-pack made fix https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/1168, likely we may not need to fix on our side, I will follow it up and update for you guys.
Made my PR as draft for now

**Comment by andreszs** [comment]
> FYI, as one contributor from impact-pack made fix [ltdrdata/ComfyUI-Impact-Pack#1168](https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/1168), likely we may not need to fix on our side, I will follow it up and update for you guys. Made my PR as draft for now

image

Unfortunately my PR does not solve the issue with Nodes 2.0, the canvas does not show up. I really wanted to create the PR with Nodes 2.0 compatibility, but I didn't want to delay the PR any longer.

If this is merged with the old nodes, I'll ask GPT to refactor my PR to include Nodes 2.0 support from this PR sometime during next week, to have a fullly working version, compatible with Nodes 2.0 + INT inputs from primitive nodes.

**Comment by jtydhr88** [comment]
@andreszs, do you know when your PR https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/1168 can be merged?

**Comment by andreszs** [comment]
> @andreszs, do you know when your PR [ltdrdata/ComfyUI-Impact-Pack#1168](https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/1168) can be merged?

It's ready for merging any time.
