### PR TITLE
fix: update upload dialog status when async download completes

### LINKED ISSUE #10609: Upload Model dialog can remain stuck in Processing after async download finishes
## Summary

When the model import flow returns an async upload/download task, the dialog switches to `Processing`, but it does not transition to `Success` or `Error` when that specific task later completes.

As a result, the dialog can keep showing `Processing` even after the model import already finished.

## Current behavior

In the upload flow:

- `uploadAssetAsync(...)` can return an async task
- the dialog moves to step 3 and sets the status to `processing`
- later completion/failure of that task does not automatically update the dialog result

User-visible symptoms:

- the dialog keeps showing `Processing` after the import already finished
- the imported model may already appear in Assets / model lists while the dialog still says it is processing
- failures can be hidden until the user closes and reopens the dialog

## Expected behavior

The dialog should track the returned `task_id` and automatically transition to:

- `success` when that task completes
- `error` when that task fails

On success, it should also refresh the relevant model caches so newly imported models are immediately usable.

## Minimal repro

1. Open the model upload dialog
2. Import a public Hugging Face or Civitai model URL in an environment where the backend returns an async task instead of completing synchronously
3. Wait for the backend task to finish
4. Observe that the dialog can remain stuck in `Processing` instead of transitioning to success or error

## Why this matters

The current UI implies that the import is still running even when the backend has already finished. That makes the dialog unreliable and forces users to infer completion from other parts of the UI instead of from the import flow itself.

### PR DESCRIPTION
**Pull request by dante01yoon**
## Summary

- Upload Model dialog stays stuck in "Processing" after async download completes because the wizard never watches for task completion
- `useUploadModelWizard.ts` sets `uploadStatus = 'processing'` but has no watcher linking it to `assetDownloadStore.lastCompletedDownload`
- Added a `watch` on `lastCompletedDownload` that transitions `uploadStatus` to `'success'` when the tracked task finishes

- Fixes #10609

## Root Cause

`uploadModel()` (line 249) sets `uploadStatus = 'processing'` when the async task starts, but control flow ends there. The `assetDownloadStore` receives WebSocket completion events and updates `lastCompletedDownload`, but the wizard never watches this reactive state.

## Fix

Added a `watch` inside the async branch that monitors `assetDownloadStore.lastCompletedDownload`. When the completed task ID matches the upload's task ID, it transitions `uploadStatus` from `'processing'` to `'success'` and refreshes model caches. The watcher auto-disposes after firing.

## Red-Green Verification

| Commit | CI Status | Purpose |
|--------|-----------|---------|
| `test: add failing test for upload dialog stuck in processing state` | :red_circle: Red | Proves the test catches the bug |
| `fix: update upload dialog status when async download completes` | :green_circle: Green | Proves the fix resolves the bug |

## Test Plan

- [x] CI red on test-only commit
- [x] CI green on fix commit
- [x] Unit test: `updates uploadStatus to success when async download completes`
- [ ] Manual: Import model via URL → verify dialog transitions from Processing to Success (requires `--enable-assets`)

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-10838-fix-update-upload-dialog-status-when-async-download-completes-3376d73d365081b6a5b1d2be3804ce4b) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/platform/assets/composables/useUploadModelWizard.ts [hunk 1]
```diff
@@ -247,6 +247,17 @@ export function useUploadModelWizard(modelTypes: Ref<ModelTypeOption[]>) {
...
+        const stopWatch = watch(
+          () => assetDownloadStore.lastCompletedDownload,
+          async (completed) => {
+            if (completed?.taskId === result.task.task_id) {
+              uploadStatus.value = 'success'
+              await refreshModelCaches()
+              stopWatch()
+            }
+          }
+        )
```
[the remark this answers is not in the document]
Comment (dante01yoon) [reply src/platform/assets/composables/useUploadModelWizard.ts]: Addressed check again

File: src/platform/assets/composables/useUploadModelWizard.ts [hunk 2]
```diff
@@ -247,6 +249,34 @@ export function useUploadModelWizard(modelTypes: Ref<ModelTypeOption[]>) {
...
+              uploadError.value =
+                download?.error ||
+                t('assetBrowser.downloadFailed', {
+                  name: download?.assetName || ''
+                })
+              stopAsyncWatch?.()
+              stopAsyncWatch = undefined
+            }
+          }
+        )
```
Comment (dante01yoon) [inline src/platform/assets/composables/useUploadModelWizard.ts:283]: addressed

File: src/platform/assets/composables/useUploadModelWizard.test.ts [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+    const event = new CustomEvent('asset_download', { detail })
+    const { api } = await import('@/scripts/api')
+    const handler = vi
+      .mocked(api.addEventListener)
+      .mock.calls.find((c) => c[0] === 'asset_download')?.[1] as
+      | ((e: CustomEvent) => void)
+      | undefined
+
+    // If handler was registered, call it; otherwise set store state directly
+    if (handler) {
```
Comment (pythongosssss) [inline src/platform/assets/composables/useUploadModelWizard.test.ts]: This seems a bit odd to have this condition? I think the manual fallback should be removed?

**Review by pythongosssss — COMMENTED** [review]
the rabbit comment about if the initial state is already terminal seems like it could be valid to address?

**Comment by dante01yoon** [comment]
Addressed the two outstanding review items from @pythongosssss:

**1. `immediate: true` watcher race condition**

`watch()` with `{ immediate: true }` fires the callback synchronously before returning the stop handle, so `stopAsyncWatch?.()` inside the callback was a no-op when the download was already terminal. Fixed by using a local `resolved` flag — if the immediate invocation hits a terminal state, we call `stop()` on the returned handle after the `watch()` call.

**2. Removed `if (handler)` fallback in tests**

The `else` branch was dead code (`downloadList` is a computed, so `push` doesn't exist on it). Replaced with `expect(handler).toBeDefined()` + `handler!()` so the test fails explicitly if the event handler isn't registered.

**Comment by dante01yoon** [comment]
@coderabbitai approve

**Review by pythongosssss — APPROVED** [review]
