### PR TITLE
fix: node preview background color

### LINKED ISSUE #6576: The node title background color in the node preview needs to be updated.
The node title background still seems to retain the old color theme

## before

Image

## Current version(main)

Image

Image

Image

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-6576-The-node-title-background-color-in-the-node-preview-needs-to-be-updated-2a16d73d36508181b65dd7db790412cb) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by christian-byrne**
## Summary

Changes node previews to use background color from color palette instead of the menu color.

| Before | After |
| ------ | ----- |
| Selection_2345 | Selection_2347 |

Fixes https://github.com/Comfy-Org/ComfyUI_frontend/issues/6576

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-6768-fix-node-preview-background-color-2b16d73d365081868644e1e6b7c7e3be) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/components/node/NodePreview.vue [hunk 1]
```diff
@@ -3,7 +3,11 @@ https://github.com/Nuked88/ComfyUI-N-Sidebar/blob/7ae7da4a9761009fb6629bc04c6830
 -->
 <template>
   <LGraphNodePreview v-if="shouldRenderVueNodes" :node-def="nodeDef" />
-  <div v-else class="_sb_node_preview">
+  <div
+    v-else
+    class="_sb_node_preview"
+    :style="{ backgroundColor: litegraphColors.NODE_DEFAULT_COLOR }"
```
Comment (DrJKL) [inline src/components/node/NodePreview.vue]: Optional: You could also do `bg-component-node-background` in the class.

Comment (DrJKL) [inline src/components/node/NodePreview.vue]: Like this:
```suggestion
    class="_sb_node_preview bg-component-node-background"
```

Comment (christian-byrne) [reply src/components/node/NodePreview.vue]: Thank you

**Review by DrJKL — DISMISSED** [review]

**Review by DrJKL — DISMISSED** [review]

File: src/components/node/NodePreview.vue (hunk 1 above)
Comment (christian-byrne) [reply src/components/node/NodePreview.vue]: Somehow forgot, but it's only been like 10 days, haha
