### PR TITLE
fix mask editor bug under vueNodes

### LINKED ISSUE #5816: Vue node: MaskEditor is not loading the right image, and after editing the mask, the mask isn't saved correctly either.
https://github.com/user-attachments/assets/9098bfcd-6262-4d4c-b446-5d2a8e092883

Can we also change the mask icon? For non-English speakers, this icon would be very confusing.

Image

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-5816-Vue-node-MaskEditor-is-not-loading-the-right-image-and-after-editing-the-mask-the-m-27b6d73d365081aa9788e0b1797deece) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jtydhr88**
## Summary

fix mask editor issues on vueNodes

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-5953-fix-mask-editor-bug-under-vueNodes-2856d73d3650810aa8a2e1a94c4d97a6) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by comfyui-wiki** [comment]
Yes this PR fixed the https://github.com/Comfy-Org/ComfyUI_frontend/issues/5816

https://github.com/user-attachments/assets/7c3a210f-86cd-4ea1-93cb-077747725305

File: src/scripts/app.ts [hunk 1]
```diff
@@ -379,11 +379,19 @@ export class ComfyApp {
     const paintedIndex = selectedIndex + 1
     const combinedIndex = selectedIndex + 2
 
+    // for vueNodes mode
+    let images = node.images
```
Comment (DrJKL) [inline src/scripts/app.ts]: I don't like that we have `imgs` and `images` in the same scope.

Comment (DrJKL) [reply src/scripts/app.ts]: Side-nit: Could you use a nullish coalescing operator to not need the conditional or a mutable reference here?

File: src/renderer/extensions/vueNodes/components/ImagePreview.vue [hunk 2]
```diff
@@ -186,8 +187,29 @@ const handleImageError = () => {
...
+      node.imageIndex = currentIndex.value
+
+      node.imgs = await Promise.all(
+        props.imageUrls.map((url) => {
+          return new Promise<HTMLImageElement>((resolve) => {
+            const img = new Image()
+
+            img.onload = () => resolve(img)
+
+            img.src = url
```
Comment (DrJKL) [inline src/renderer/extensions/vueNodes/components/ImagePreview.vue]: @christian-byrne Is this going to run into the same CORS issue you were working on fixing for Cloud?

File: src/scripts/app.ts (hunk 1 above)
Comment (jtydhr88) [reply src/scripts/app.ts]: fixed.

File: src/renderer/extensions/vueNodes/components/ImagePreview.vue (hunk 2 above)
Comment (christian-byrne) [reply src/renderer/extensions/vueNodes/components/ImagePreview.vue]: Maybe, we could add just in case. See this for details:

- https://github.com/Comfy-Org/ComfyUI_frontend/pull/5957

Comment (jtydhr88) [reply src/renderer/extensions/vueNodes/components/ImagePreview.vue]: added

**Comment by AustinMroz** [comment]
Accessing nodeOutputs by nodeId instead of nodeLocatorId will cause the code to break when run inside of subgraphs.

But from looking into it, it's a decent amount of work to cleanup the surrounding code to use locatorIds instead of assuming the node resides in the active graph which is kinda out of scope. I can handle it in a separate PR after this one is merged.

**Review by christian-byrne — CHANGES_REQUESTED** [review]
So the fundamental issue is that, when in Litegraph, both `LoadImage` and `SaveImage` have their `imgs` property assigned when their preview/output is udpated. For `SaveImage` it is set via this code https://github.com/Comfy-Org/ComfyUI_frontend/blob/3f84bb0db213d06f881c503dc3f9677d8781c114/src/composables/node/useNodeImage.ts#L101-L116

And `useNodeImage` is invoked in the draw loop here https://github.com/Comfy-Org/ComfyUI_frontend/blob/3f84bb0db213d06f881c503dc3f9677d8781c114/src/services/litegraphService.ts#L872-L896

But for `LoadImage`, I guess it is set in the `useNodeImageUpload` widget logic (which Vue nodes don't have). So, in Vue mode, only the `SaveImage` is getting `node.imgs` set. Then, the solution in this PR involves getting the image, initializing the `Image` object, then setting it manually. 

A few questions:

1. Should this logic go into its own function? Being a side-effect of `handleEditMask` is fairly confusing and I don't think future maintainers will understand the logic and what is happening
2. Do we need to create a new `Image` object? Aren't we doubling the work? Can we not just do this:

  ```vue
  <template>
    <img
      v-for="(url, i) in imageUrls"
      :key="i"
      :src="url"
      ref="imageEls"
      class="..."
    />
  </template>
  
  <script setup lang="ts">
  const imageEls = ref<HTMLImageElement[]>([])
  
  const handleEditMask = async () => {
    if (!props.nodeId) return
    const node = app.rootGraph?.getNodeById(props.nodeId)
    if (!node) return
  
    node.imageIndex = currentIndex.value
    node.imgs = imageEls.value          // ← already HTMLImageElements
    app.canvas?.selectNode(node)
    await commandStore.execute('Comfy.MaskEditor.OpenMaskEditor')
  }
  </script>
  ```

File: src/scripts/app.ts [hunk 3]
```diff
@@ -410,7 +414,8 @@ export class ComfyApp {
           ComfyApp.clipspace.imgs[ComfyApp.clipspace.combinedIndex].src
       }
       if (ComfyApp.clipspace.imgs && node.imgs) {
-        if (node.images && ComfyApp.clipspace.images) {
+        // Update node.images even if it's initially undefined (vueNodes mode)
+        if (ComfyApp.clipspace.images) {
```
[the remark this answers is not in the document]
Comment (jtydhr88) [reply src/scripts/app.ts:419]: we need to remove this confition as under VueNodes, node.images will be undefined and need to be updated

File: src/scripts/app.ts [hunk 4]
```diff
@@ -512,6 +517,13 @@ export class ComfyApp {
       }
 
       app.graph.setDirtyCanvas(true)
+
+      if (node.images && app.nodeOutputs[node.id]) {
+        useNodeOutputStore().nodeOutputs[node.id] = {
```
[the remark this answers is not in the document]
Comment (jtydhr88) [reply src/scripts/app.ts]: fixed

File: src/renderer/extensions/vueNodes/components/ImagePreview.vue [hunk 5]
```diff
@@ -43,6 +43,16 @@
...
 
+      <!-- Hidden preloaded images for mask editor -->
+      <img
+        v-for="(url, i) in imageUrls"
+        v-show="false"
+        :key="i"
+        ref="imageEls"
+        :src="url"
+        alt=""
+      />
```
Comment (christian-byrne) [inline src/renderer/extensions/vueNodes/components/ImagePreview.vue]: This feels like it might be slightly suboptimal since we are creating extra `img`

```vue
      <!-- Main Image -->
      <img
        v-else
        :src="currentImageUrl"
        :alt="imageAltText"
        class="block h-[352px] w-full object-contain"
        @load="handleImageLoad"
        @error="handleImageError"
      />
```

```vue
      <!-- Hidden preloaded images for mask editor -->
      <img
        v-for="(url, i) in imageUrls"
        v-show="false"
        :key="i"
        ref="imageEls"
        :src="url"
        alt=""
      />
```

Is the problem just that we are not loading the other images? I just tested running default workflow with batch size of 4, and when I open a mask editor from the node, it only shows the "active" image anyway, so I think we can just use the active image and not create a second `img` component. WDYT?

**Review by christian-byrne — CHANGES_REQUESTED** [review]

File: src/renderer/extensions/vueNodes/components/ImagePreview.vue (hunk 5 above)
Comment (jtydhr88) [reply src/renderer/extensions/vueNodes/components/ImagePreview.vue]: fixed

File: src/renderer/extensions/vueNodes/components/ImagePreview.vue [hunk 6]
```diff
@@ -182,7 +186,18 @@ const handleImageError = () => {
...
 }
 
+// In vueNodes mode, we need to set them manually before opening the mask editor.
+const setupNodeForMaskEditor = () => {
+  if (!props.nodeId || !currentImageEl.value) return
+  const node = app.rootGraph?.getNodeById(props.nodeId)
+  if (!node) return
+  node.imageIndex = currentIndex.value
+  node.imgs = [currentImageEl.value]
+  app.canvas?.select(node)
```
Comment (christian-byrne) [inline src/renderer/extensions/vueNodes/components/ImagePreview.vue:196]: This is necessary? How can the node be unselected if this is being called?

Comment (jtydhr88) [reply src/renderer/extensions/vueNodes/components/ImagePreview.vue:196]: image
Yes, this is necessary, please check the screenshot. In this case, even if no node is selected, the user may still see the icon to open the mask editor when hovering the mouse over the image. However, because no node is currently selected, the mask editor cannot be opened in this situation, since the mask editor requires accessing the selected node.

**Review by christian-byrne — APPROVED** [review]
LGTM!

**Comment by christian-byrne** [comment]
In follow up (when we have time), we can do:

Add something to keep in sync with `LGraphNode.images` for compatibility generally, following some pattern similar to

```typescript
watch(
  () => props.imageUrls,
  (newUrls) => {
    const node = app.graph.getNodeById(props.nodeId)
    if (!node) return

    node.images = [currentImageEl] as string[]
  },
  { deep: true, flush: 'post' }
)
```

Then we can just remove this, which might be a little bit confusingly named currently: https://github.com/Comfy-Org/ComfyUI_frontend/blob/bee09d5310409ae15d550995296224ec4a887c29/src/stores/imagePreviewStore.ts#L334-L352
