### PR TITLE
[3d] better solution to support reading extra resource/texture

### LINKED ISSUE #4101: [Bug]: Load3D loading issues
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Frontend Version

comfyui-frontend-package==1.21.7

### Expected Behavior

Textures should load.

### Actual Behavior

Textures don't load.

### Steps to Reproduce

I'm having some issues using the Load3D node in ComfyUI, running locally on my computer. 

First, external textures don't load for FBX or GLTF/GLTB files.  I assume it's not looking in the correct location for these files. All of my texture files are stored in the local ComfyUI folder input/3d.

Error for loading FBX files:
GET http://127.0.0.1:8188/api/texmap.png	[HTTP/1.1 404 Not Found 0ms]

Error for loading GLTF/GLTB files:
THREE.GLTFLoader: Couldn't load texture texmap.png    GLTFLoader.js:3331:11

Second issue, GLTF files that store external buffer data in .bin files don't load.  Again, I assume it's not looking in the
correct location, and not necessary an issue with loading the .bin file itself.

Error loading model: Error: THREE.GLTFLoader: Failed to load buffer "box_test0.bin".

Third issue, FBX files that store mesh-only data (no skeletal bones) don't load.  Not sure why bones are required here,
as other formats like Wavefront and STL don't use bones.

Error loading model: TypeError: skeleton.bones[boneIndex] is undefined
    applyBoneTransform three.module.js:33052
    getVertexPosition three.module.js:32953
    computeBoundingBox three.module.js:32867
    expandByObject three.module.js:4889
    expandByObject three.module.js:4922
    setFromObject three.module.js:4771
    setupModel ModelManager.ts:730
    loadModel LoaderManager.ts:86
    loadModel Load3d.ts:382
    onchange load3d.ts:140

What does work:
- FBX files with embedded textures load.
- GLTF/GLTB files with embedded textures and embedded buffer data load.
- Wavefront OBJ files and MAT files with external textures load.

I did read that some recent changes were made to add support for Wavefront MAT files, and that works.
So I think the same support needs to be added for FBX and GLTF/GLTB files to read external texture files in the input/3d folder.

### Debug Logs

```powershell
none
```

### Browser Logs

GET http://127.0.0.1:8188/api/texmap.png	[HTTP/1.1 404 Not Found 0ms]

THREE.GLTFLoader: Couldn't load texture texmap.png    GLTFLoader.js:3331:11

Error loading model: TypeError: skeleton.bones[boneIndex] is undefined
    applyBoneTransform three.module.js:33052
    getVertexPosition three.module.js:32953
    computeBoundingBox three.module.js:32867
    expandByObject three.module.js:4889
    expandByObject three.module.js:4922
    setFromObject three.module.js:4771
    setupModel ModelManager.ts:730
    loadModel LoaderManager.ts:86
    loadModel Load3d.ts:382
    onchange load3d.ts:140

### Setting JSON

default

### What browsers do you use to access the UI ?

Mozilla Firefox

### Other Information

Using:
ComfyUI v0.3.40
comfyui-frontend-package==1.21.7

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-4101-Bug-Load3D-loading-issues-20c6d73d365081768042cb995e80a2be) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jtydhr88**
just find out a correct way to handle extra resource/texture reading for 3d model, rather than writting an override class.
Tested on:
OBJ+MTL
image

GLTF+Extra Texture
image

FBX+Extra Texture
image

Resolved https://github.com/Comfy-Org/ComfyUI_frontend/issues/4101

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-4209-3d-better-solution-to-support-reading-extra-resource-texture-2156d73d365081b3b790c5cd0949f5d0) by [Unito](https://www.unito.io)

### CODE REVIEW

File: src/extensions/core/load3d/LoaderManager.ts [hunk 1]
```diff
@@ -100,9 +92,27 @@ export class LoaderManager implements LoaderManagerInterface {
...
 
+    const filename = new URLSearchParams(url.split('?')[1]).get('filename')
+
+    if (!filename) {
+      return null
+    }
+
+    const loadRootFolder = new URLSearchParams(url.split('?')[1]).get('type')
+
+    const subfolder = new URLSearchParams(url.split('?')[1]).get('subfolder')
```
Comment (webfiltered) [inline src/extensions/core/load3d/LoaderManager.ts]:
```suggestion
    // Parse URL parameters once
    const params = new URLSearchParams(url.split('?')[1])

    const filename = params.get('filename')
    if (!filename) {
      console.error('Missing filename in URL:', url)
      return null
    }

    const loadRootFolder = params.get('type') === 'output' ? 'output' : 'input'
    const subfolder = params.get('subfolder')
```

- Prefer error logging over silent failure
- Only allow input/output
- Remove redundant code

File: src/extensions/core/load3d/LoaderManager.ts [hunk 2]
```diff
@@ -100,9 +92,27 @@ export class LoaderManager implements LoaderManagerInterface {
...
+
+    const path =
+      'api/view?type=' +
+      loadRootFolder +
+      '&subfolder=' +
+      subfolder +
```
Comment (webfiltered) [inline src/extensions/core/load3d/LoaderManager.ts]:
```suggestion
      encodeURIComponent(subfolder) +
```

URL encode input

**Review by webfiltered — CHANGES_REQUESTED** [review]
Good to go w/nits!

File: src/extensions/core/load3d/LoaderManager.ts (hunk 1 above)
Comment (jtydhr88) [reply src/extensions/core/load3d/LoaderManager.ts]: fixed

File: src/extensions/core/load3d/LoaderManager.ts (hunk 2 above)
Comment (jtydhr88) [reply src/extensions/core/load3d/LoaderManager.ts]: fixed

**Comment by jtydhr88** [comment]
After a period of testing, I found that in order to better implement this texture modification, we still need to support uploading models and their corresponding resources to different folders. Previously, all model files would be uploaded to the '3d' folder, and during the upload process, files with duplicate names would be automatically renamed. As for resource files, they needed to be manually copied to the 3d folder, which created a problem where files with the same names would be overwritten. Therefore, a better approach is to allow users to upload different models and their corresponding resources to different subfolders. This is the change implemented in this PR.
Demo is

https://github.com/user-attachments/assets/3fc3fc8e-aa9e-47c3-8147-81aad6633cf0

need BE change https://github.com/comfyanonymous/ComfyUI/pull/8597

**Review by christian-byrne — APPROVED** [review]
LGTM
