### PR TITLE
fix: restore mask editor compatibility with Impact-Pack plugin

### LINKED ISSUE #7665: Preview Bridge (Image) from Impact pack Broken
### What happened?

the very vital Preview Bridge (from Impack pack https://github.com/ltdrdata/ComfyUI-Impact-Pack), won't load the mask editor. I think this is front end rather than the node. Might be trelated to the other mask editor issues, not sure. Can't test without custom nodes for obvious reasons!

### Steps to Reproduce

1. Load Preview bridge run an image into it a attempt to use mask editor... or image canvas if you wish.

### How is this affecting you?

Workflow won't execute

### ComfyUI Frontend Version

latest

### Browser

Chrome/Chromium

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-7665-Preview-Bridge-Broken-2cf6d73d365081a98d19fb65799da0f1) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jtydhr88**
## Summary

- Skip widget filenames starting with '$' (internal reference format)
- Add deprecated ComfyApp.open_maskeditor for plugin compatibility
- Register MaskEditor button in ClipspaceDialog

fix https://github.com/Comfy-Org/ComfyUI_frontend/issues/7665 and 
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1165
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1158
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/1157

## Screenshots (if applicable)
before

https://github.com/user-attachments/assets/356dd920-8b64-40f4-8839-90b955ffafc3

after

https://github.com/user-attachments/assets/dff9abcd-530a-4995-bb4b-51f408d4eca9

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-7762-fix-restore-mask-editor-compatibility-with-Impact-Pack-plugin-2d46d73d36508199bdaecbd5ba838483) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by christian-byrne — COMMENTED** [review]
This looks good and definitely we should solve this. Question: would it also be solveable by updating Impact-Pack to use the modern APIs like the commands system?

File: src/extensions/core/maskeditor.ts [hunk 1]
```diff
@@ -78,7 +100,23 @@ app.registerExtension({
       label: 'Decrease Brush Size in MaskEditor',
       function: () => changeBrushSize((old) => _.clamp(old - 4, 1, 100))
     }
-  ]
+  ],
+  init() {
+    // Set up ComfyApp static methods for plugin compatibility (deprecated)
+    ComfyApp.open_maskeditor = openMaskEditorFromClipspace
+    ComfyApp.maskeditor_is_opended = isOpened
```
Comment (DrJKL) [inline src/extensions/core/maskeditor.ts]: Typo?

Comment (jtydhr88) [reply src/extensions/core/maskeditor.ts]: no, not typo, it comes from original design before I refactored, see image

**Comment by jtydhr88** [comment]
> This looks good and definitely we should solve this. Question: would it also be solveable by updating Impact-Pack to use the modern APIs like the commands system?

I prefer to fix on our side fro now, because we don't know is any other custom nodes using these (deprecated) apis

**Review by brucew4yn3rp — DISMISSED** [review]

**Review by christian-byrne — APPROVED** [review]

**Comment by zslefour** [comment]
I use ComfyUI_windows_portable_nvidia_cu128.7z v0.6.0 packge, update comfyui-frontend-package to 1.37.0 , Impact-Pack Preview Bridge still unable to open mask edit .

**Comment by flyingshutter** [comment]
@zslefour confirmed. Today I tried with v1.37.1 and mask editor works.
The pull request was merged after v1.37.0
